.TH cg-autobin.pl 1 2014-05-07 "" ""
.SH NAME
cg-autobin.pl \- This application is part of (
.B cg3
)
.PP
This tool is part of the CG-3
constraint grammar system: \fBhttps://visl.sdu.dk/cg3.html\fR.
.SH SYNOPSIS
.B cg-autobin.pl
[OPTIONS]
.SH DESCRIPTION
.BR cg-autobin.pl
is a thin wrapper around \fBvislcg3(1)\fR to automatically compile
textual grammars to binary form for faster loading, if the textual grammar
was changed since last run.
Used as a middle ground between development and end-user distribution.
.RE
.SH SEE ALSO
.I vislcg3\fR(1)
.SH BUGS
Email to: Tino Didriksen <mail@tinodidriksen.com>
.SH AUTHOR
(c) 2007-2014 GrammarSoft ApS

