language: cpp

addons:
  apt:
    packages:
      - cmake
      - libboost-dev
      - libicu-dev
      - swig

before_script:
  - cmake -DENABLE_PYTHON_BINDINGS=ON .

script:
  - $CXX --version
  - export V=1 VERBOSE=1
  - cmake --build . -j 4
  - ./test/runall.pl
  - sudo cmake --install .
