sudo: required
dist: xenial
language: cpp

addons:
  apt:
    packages:
      - cmake
      - libboost-dev
      - libicu-dev
      - swig

before_script:
  - cmake -DENABLE_PYTHON_BINDINGS=ON .

script:
  - $CXX --version
  - make -j2
  - ./test/runall.pl
