sudo: false
language: cpp

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libboost1.48-dev
      - libicu-dev

compiler:
  - clang
  - gcc

before_script:
  - cmake .

script:
  - $CXX --version
  - make -j2
  - ./test/runall.pl
