.TH cg-comp 1 2007-04-10 "" ""
.SH NAME
cg-comp \- This application is part of (
.B vislcg3
)
.PP
This tool is part of the vislcg3
constraint grammar system: \fBhttp://beta.visl.sdu.dk/cg3.html\fR.
.SH SYNOPSIS
.B cg-comp
[
.B \-v \fR|
.B \-h
] grammar_file [input_file [output_file]]
.SH DESCRIPTION
.BR cg-comp 
is the program used to compile constraint grammars in a text format
to a binary format that results in faster load times. It reads the 
grammar file from \fBinput_file\fR and writes output
to \fBoutput_file\fR. The binary grammar files generated can be used 
in the \fBcg\-proc(1)\fR disambiguator.
.RE
.SH OPTIONS
.TP
\fB\-v\fR, \fB\-\-version\fR:
version
.TP
\fB\-h\fR, \fB\-\-help\fR:
show this help
.RS
.SH SEE ALSO
.I cg-proc\fR(1),
.SH BUGS
Email to: tino <at> didriksen.cc
.SH AUTHOR
(c) 2007--2008 GrammarSoft ApS

