/* Generated by re2c 0.11.0 on Wed Mar 14 00:27:00 2007 */
/*
 * Copyright (C) 2006, GrammarSoft Aps
 * and the VISL project at the University of Southern Denmark.
 * All Rights Reserved.
 *
 * The contents of this file are subject to the GrammarSoft Public
 * License Version 1.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of
 * the License at http://www.grammarsoft.com/GSPL or
 * http://visl.sdu.dk/GSPL.txt
 * 
 * Software distributed under the License is distributed on an "AS
 * IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * rights and limitations under the License.
 */

#include "GPRE2C.h"

using namespace CG3;
using namespace CG3::Strings;
#define YYCURSOR        input



YYCTYPE *GPRE2C::skipline(YYCTYPE *input) {
skipline_start:

{
	YYCTYPE yych;

	yych = *YYCURSOR;
	if(yych <= 0x0000000C) {
		if(yych <= 0x00000009) {
			if(yych >= 0x00000001) goto yy6;
		} else {
			if(yych == 0x0000000B) goto yy6;
			goto yy4;
		}
	} else {
		if(yych <= 0x00002027) {
			if(yych == 0x00000085) goto yy4;
			goto yy6;
		} else {
			if(yych <= 0x00002029) goto yy4;
			if(yych <= 0x0000FFFF) goto yy6;
		}
	}
	++YYCURSOR;
	{goto skipline_end;}
yy4:
	++YYCURSOR;
	{result->lines++; goto skipline_end;}
yy6:
	++YYCURSOR;
	{goto skipline_start;}
}

skipline_end:
	return YYCURSOR;
}

YYCTYPE *GPRE2C::parseCompositeTag(YYCTYPE *input, Set *set) {
	CG3::CompositeTag *ctag = result->allocateCompositeTag();
	marker = YYCURSOR;

parseCompositeTag_start:

{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if(yych <= '\'') {
		if(yych <= 0x0000000C) {
			if(yych <= 0x00000009) {
				if(yych <= 0x00000000) goto yy10;
				if(yych <= 0x00000008) goto yy14;
				goto yy25;
			} else {
				if(yych == 0x0000000B) goto yy25;
				goto yy12;
			}
		} else {
			if(yych <= ' ') {
				if(yych <= 0x0000000D) goto yy25;
				if(yych <= 0x0000001B) goto yy14;
				goto yy25;
			} else {
				if(yych == '#') goto yy17;
				goto yy14;
			}
		}
	} else {
		if(yych <= '\\') {
			if(yych <= ':') {
				if(yych <= '(') goto yy19;
				if(yych <= ')') goto yy21;
				goto yy14;
			} else {
				if(yych <= ';') goto yy23;
				if(yych <= '[') goto yy14;
				goto yy16;
			}
		} else {
			if(yych <= 0x00002027) {
				if(yych == 0x00000085) goto yy12;
				goto yy14;
			} else {
				if(yych <= 0x00002029) goto yy12;
				if(yych <= 0x0000FFFF) goto yy14;
			}
		}
	}
yy10:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy28;
			if(yych >= 0x0000000E) goto yy28;
		} else {
			if(yych <= ' ') goto yy11;
			if(yych != '#') goto yy28;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy11;
			if(yych != ';') goto yy28;
		} else {
			if(yych <= 0x00000085) goto yy11;
			if(yych <= 0x00002027) goto yy28;
			if(yych >= 0x0000202A) goto yy28;
		}
	}
yy11:
	{goto parseCompositeTag_end;}
yy12:
	++YYCURSOR;
	{
		marker = YYCURSOR;
		result->lines++;
		goto parseCompositeTag_start;
		}
yy14:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy28;
yy15:
	{
		size_t length = (YYCURSOR - marker)+1;
		YYCTYPE *buffer = new YYCTYPE[length];
		buffer[length-1] = 0;
		u_strncpy(buffer, marker, (int32_t)length-1);
		CG3::Tag *tag = result->allocateTag(buffer);
		result->addTagToCompositeTag(tag, ctag);
		delete buffer;
		marker = YYCURSOR;
		goto parseCompositeTag_start;
		}
yy16:
	yych = *++YYCURSOR;
	if(yych <= '\'') {
		if(yych == '#') goto yy27;
		goto yy28;
	} else {
		if(yych <= ')') goto yy27;
		if(yych == ';') goto yy27;
		goto yy28;
	}
yy17:
	++YYCURSOR;
	{
		YYCURSOR = skipline(YYCURSOR);
		marker = YYCURSOR;
		goto parseCompositeTag_start;
		}
yy19:
	++YYCURSOR;
	{u_fprintf(ux_stderr, "Error: Mismatched ( on line %u!\n", result->lines); exit(1);}
yy21:
	++YYCURSOR;
	{goto parseCompositeTag_end;}
yy23:
	++YYCURSOR;
	{u_fprintf(ux_stderr, "Error: Found ; before ) on line %u!\n", result->lines); exit(1);}
yy25:
	++YYCURSOR;
	{
		marker = YYCURSOR;
		goto parseCompositeTag_start;
		}
yy27:
	++YYCURSOR;
	yych = *YYCURSOR;
yy28:
	if(yych <= ')') {
		if(yych <= ' ') {
			if(yych <= 0x00000008) goto yy27;
			if(yych <= 0x0000000D) goto yy15;
			if(yych <= 0x0000001B) goto yy27;
			goto yy15;
		} else {
			if(yych == '#') goto yy15;
			if(yych <= '\'') goto yy27;
			goto yy15;
		}
	} else {
		if(yych <= '\\') {
			if(yych == ';') goto yy15;
			if(yych <= '[') goto yy27;
		} else {
			if(yych <= 0x00000085) {
				if(yych <= 0x00000084) goto yy27;
				goto yy15;
			} else {
				if(yych <= 0x00002027) goto yy27;
				if(yych <= 0x00002029) goto yy15;
				goto yy27;
			}
		}
	}
yy29:
	++YYCURSOR;
	yych = *YYCURSOR;
	if(yych <= '[') {
		if(yych <= 0x0000000D) {
			if(yych <= 0x00000008) goto yy27;
			goto yy15;
		} else {
			if(yych <= 0x0000001B) goto yy27;
			if(yych <= ' ') goto yy15;
			goto yy27;
		}
	} else {
		if(yych <= 0x00000085) {
			if(yych <= '\\') goto yy29;
			if(yych <= 0x00000084) goto yy27;
			goto yy15;
		} else {
			if(yych <= 0x00002027) goto yy27;
			if(yych <= 0x00002029) goto yy15;
			goto yy27;
		}
	}
}


parseCompositeTag_end:
	if (ctag->tags_map.empty()) {
		u_fprintf(ux_stderr, "Error: Empty () on line %u!\n", result->lines);
		exit(1);
	}
	result->addCompositeTagToSet(set, ctag);
	return YYCURSOR;
}

YYCTYPE *GPRE2C::parseInlineSet(YYCTYPE *input, Set **ret_set) {
	CG3::Set *curset = result->allocateSet();
	curset->line = result->lines;
	curset->setName((uint32_t)0);
	CG3::CompositeTag *ctag = result->allocateCompositeTag();
	marker = YYCURSOR;

parseInlineSet_start:

{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if(yych <= '\'') {
		if(yych <= 0x0000000C) {
			if(yych <= 0x00000009) {
				if(yych <= 0x00000000) goto yy33;
				if(yych <= 0x00000008) goto yy37;
				goto yy48;
			} else {
				if(yych == 0x0000000B) goto yy48;
				goto yy35;
			}
		} else {
			if(yych <= ' ') {
				if(yych <= 0x0000000D) goto yy48;
				if(yych <= 0x0000001B) goto yy37;
				goto yy48;
			} else {
				if(yych == '#') goto yy40;
				goto yy37;
			}
		}
	} else {
		if(yych <= '\\') {
			if(yych <= ':') {
				if(yych <= '(') goto yy42;
				if(yych <= ')') goto yy44;
				goto yy37;
			} else {
				if(yych <= ';') goto yy46;
				if(yych <= '[') goto yy37;
				goto yy39;
			}
		} else {
			if(yych <= 0x00002027) {
				if(yych == 0x00000085) goto yy35;
				goto yy37;
			} else {
				if(yych <= 0x00002029) goto yy35;
				if(yych <= 0x0000FFFF) goto yy37;
			}
		}
	}
yy33:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy51;
			if(yych >= 0x0000000E) goto yy51;
		} else {
			if(yych <= ' ') goto yy34;
			if(yych != '#') goto yy51;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy34;
			if(yych != ';') goto yy51;
		} else {
			if(yych <= 0x00000085) goto yy34;
			if(yych <= 0x00002027) goto yy51;
			if(yych >= 0x0000202A) goto yy51;
		}
	}
yy34:
	{goto parseInlineSet_end;}
yy35:
	++YYCURSOR;
	{marker = YYCURSOR; result->lines++; goto parseInlineSet_start;}
yy37:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy51;
yy38:
	{
		size_t length = (YYCURSOR - marker)+1;
		YYCTYPE *buffer = new YYCTYPE[length];
		buffer[length-1] = 0;
		u_strncpy(buffer, marker, (int32_t)length-1);
		CG3::Tag *tag = result->allocateTag(buffer);
		result->addTagToCompositeTag(tag, ctag);
		delete buffer;
		marker = YYCURSOR;
		goto parseInlineSet_start;
		}
yy39:
	yych = *++YYCURSOR;
	if(yych <= '\'') {
		if(yych == '#') goto yy50;
		goto yy51;
	} else {
		if(yych <= ')') goto yy50;
		if(yych == ';') goto yy50;
		goto yy51;
	}
yy40:
	++YYCURSOR;
	{YYCURSOR = skipline(YYCURSOR);marker = YYCURSOR;goto parseInlineSet_start;}
yy42:
	++YYCURSOR;
	{u_fprintf(ux_stderr, "Error: Mismatched ( on line %u!\n", result->lines); exit(1);}
yy44:
	++YYCURSOR;
	{goto parseInlineSet_end;}
yy46:
	++YYCURSOR;
	{u_fprintf(ux_stderr, "Error: Found ; before ) on line %u!\n", result->lines); exit(1);}
yy48:
	++YYCURSOR;
	{
		marker = YYCURSOR;
		goto parseInlineSet_start;
		}
yy50:
	++YYCURSOR;
	yych = *YYCURSOR;
yy51:
	if(yych <= ')') {
		if(yych <= ' ') {
			if(yych <= 0x00000008) goto yy50;
			if(yych <= 0x0000000D) goto yy38;
			if(yych <= 0x0000001B) goto yy50;
			goto yy38;
		} else {
			if(yych == '#') goto yy38;
			if(yych <= '\'') goto yy50;
			goto yy38;
		}
	} else {
		if(yych <= '\\') {
			if(yych == ';') goto yy38;
			if(yych <= '[') goto yy50;
		} else {
			if(yych <= 0x00000085) {
				if(yych <= 0x00000084) goto yy50;
				goto yy38;
			} else {
				if(yych <= 0x00002027) goto yy50;
				if(yych <= 0x00002029) goto yy38;
				goto yy50;
			}
		}
	}
yy52:
	++YYCURSOR;
	yych = *YYCURSOR;
	if(yych <= '[') {
		if(yych <= 0x0000000D) {
			if(yych <= 0x00000008) goto yy50;
			goto yy38;
		} else {
			if(yych <= 0x0000001B) goto yy50;
			if(yych <= ' ') goto yy38;
			goto yy50;
		}
	} else {
		if(yych <= 0x00000085) {
			if(yych <= '\\') goto yy52;
			if(yych <= 0x00000084) goto yy50;
			goto yy38;
		} else {
			if(yych <= 0x00002027) goto yy50;
			if(yych <= 0x00002029) goto yy38;
			goto yy50;
		}
	}
}


parseInlineSet_end:
	result->addCompositeTagToSet(curset, ctag);
	result->addSet(curset);
	*ret_set = curset;
	return YYCURSOR;
}

YYCTYPE *GPRE2C::parseSetList(YYCTYPE *input, Set *set) {
	bool want_set = true;
	marker = YYCURSOR;
	if (result->lines == 1333) {
		input=input;
	}

parseSetList_start:

{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if(yych <= '-') {
		if(yych <= ' ') {
			if(yych <= 0x0000000A) {
				if(yych <= 0x00000000) goto yy56;
				if(yych <= 0x00000008) goto yy64;
				if(yych <= 0x00000009) goto yy71;
				goto yy58;
			} else {
				if(yych <= 0x0000000C) {
					if(yych <= 0x0000000B) goto yy71;
					goto yy58;
				} else {
					if(yych <= 0x0000000D) goto yy71;
					if(yych <= 0x0000001B) goto yy64;
					goto yy71;
				}
			}
		} else {
			if(yych <= '\'') {
				if(yych <= '!') goto yy60;
				if(yych == '#') goto yy65;
				goto yy64;
			} else {
				if(yych <= ')') {
					if(yych <= '(') goto yy67;
					goto yy69;
				} else {
					if(yych == ',') goto yy64;
					goto yy60;
				}
			}
		}
	} else {
		if(yych <= 'n') {
			if(yych <= 'O') {
				if(yych == ';') goto yy73;
				if(yych <= 'N') goto yy64;
				goto yy62;
			} else {
				if(yych <= '\\') {
					if(yych <= '[') goto yy64;
					goto yy66;
				} else {
					if(yych == '^') goto yy60;
					goto yy64;
				}
			}
		} else {
			if(yych <= 0x00000084) {
				if(yych <= 'o') goto yy62;
				if(yych == '|') goto yy60;
				goto yy64;
			} else {
				if(yych <= 0x00002027) {
					if(yych <= 0x00000085) goto yy58;
					goto yy64;
				} else {
					if(yych <= 0x00002029) goto yy58;
					if(yych <= 0x0000FFFF) goto yy64;
				}
			}
		}
	}
yy56:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ')') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy76;
			if(yych >= 0x0000000E) goto yy76;
		} else {
			if(yych <= ' ') goto yy57;
			if(yych <= '\'') goto yy76;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych != ';') goto yy76;
		} else {
			if(yych <= 0x00000085) goto yy57;
			if(yych <= 0x00002027) goto yy76;
			if(yych >= 0x0000202A) goto yy76;
		}
	}
yy57:
	{goto parseSetList_end;}
yy58:
	++YYCURSOR;
	{marker = YYCURSOR; result->lines++; goto parseSetList_start;}
yy60:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ')') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy76;
			if(yych >= 0x0000000E) goto yy76;
		} else {
			if(yych <= ' ') goto yy61;
			if(yych <= '\'') goto yy76;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych != ';') goto yy76;
		} else {
			if(yych <= 0x00000085) goto yy61;
			if(yych <= 0x00002027) goto yy76;
			if(yych >= 0x0000202A) goto yy76;
		}
	}
yy61:
	{
		size_t length = (YYCURSOR - marker)+1;
		YYCTYPE *buffer = new YYCTYPE[length];
		buffer[length-1] = 0;
		u_strncpy(buffer, marker, (int32_t)length-1);
		if (want_set) {
			u_fprintf(ux_stderr, "Error: Missing set for operator %S on line %u!\n", buffer, result->lines);
			exit(1);
		}
		uint32_t set_op = ux_isSetOp(buffer);
		set->set_ops.push_back(set_op);
		want_set = true;
		marker = YYCURSOR;
		goto parseSetList_start;
		}
yy62:
	++YYCURSOR;
	if((yych = *YYCURSOR) == 'R') goto yy79;
	if(yych == 'r') goto yy79;
	goto yy76;
yy63:
	{
		if (!want_set) {
			return YYCURSOR;
		}
		size_t length = (YYCURSOR - marker)+1;
		YYCTYPE *buffer = new YYCTYPE[length];
		buffer[length-1] = 0;
		u_strncpy(buffer, marker, (int32_t)length-1);
		uint32_t set_hash = hash_sdbm_uchar(buffer, 0);
		if (result->set_alias.find(set_hash) != result->set_alias.end()) {
			set_hash = result->set_alias[set_hash];
		}
		set_hash = result->getSet(set_hash)->hash;
		set->sets.push_back(set_hash);
		delete buffer;
		marker = YYCURSOR;
		want_set = false;
		goto parseSetList_start;
		}
yy64:
	yych = *++YYCURSOR;
	goto yy76;
yy65:
	yych = *++YYCURSOR;
	goto yy76;
yy66:
	yych = *++YYCURSOR;
	if(yych <= '\'') goto yy76;
	if(yych <= ')') goto yy75;
	if(yych == ';') goto yy75;
	goto yy76;
yy67:
	++YYCURSOR;
	{
		if (!want_set) {
			return YYCURSOR;
		}
		Set *ret_set = 0;
		YYCURSOR = parseInlineSet(YYCURSOR, &ret_set);
		uint32_t set_hash = ret_set->hash;
		if (result->set_alias.find(set_hash) != result->set_alias.end()) {
			set_hash = result->set_alias[set_hash];
		}
		set->sets.push_back(set_hash);
		marker = YYCURSOR;
		want_set = false;
		goto parseSetList_start;
		}
yy69:
	++YYCURSOR;
	{u_fprintf(ux_stderr, "Error: Mismatched ) on line %u!\n", result->lines); exit(1);}
yy71:
	++YYCURSOR;
	{marker = YYCURSOR; goto parseSetList_start;}
yy73:
	++YYCURSOR;
	{goto parseSetList_end;}
yy75:
	++YYCURSOR;
	yych = *YYCURSOR;
yy76:
	if(yych <= ':') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy75;
			if(yych <= 0x0000000D) goto yy63;
			goto yy75;
		} else {
			if(yych <= ' ') goto yy63;
			if(yych <= '\'') goto yy75;
			if(yych <= ')') goto yy63;
			goto yy75;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ';') goto yy63;
			if(yych != '\\') goto yy75;
		} else {
			if(yych <= 0x00000085) goto yy63;
			if(yych <= 0x00002027) goto yy75;
			if(yych <= 0x00002029) goto yy63;
			goto yy75;
		}
	}
yy77:
	++YYCURSOR;
	yych = *YYCURSOR;
	if(yych <= '[') {
		if(yych <= 0x0000000D) {
			if(yych <= 0x00000008) goto yy75;
			goto yy63;
		} else {
			if(yych <= 0x0000001B) goto yy75;
			if(yych <= ' ') goto yy63;
			goto yy75;
		}
	} else {
		if(yych <= 0x00000085) {
			if(yych <= '\\') goto yy77;
			if(yych <= 0x00000084) goto yy75;
			goto yy63;
		} else {
			if(yych <= 0x00002027) goto yy75;
			if(yych <= 0x00002029) goto yy63;
			goto yy75;
		}
	}
yy79:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ')') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy76;
			if(yych <= 0x0000000D) goto yy61;
			goto yy76;
		} else {
			if(yych <= ' ') goto yy61;
			if(yych <= '\'') goto yy76;
			goto yy61;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych == ';') goto yy61;
			goto yy76;
		} else {
			if(yych <= 0x00000085) goto yy61;
			if(yych <= 0x00002027) goto yy76;
			if(yych <= 0x00002029) goto yy61;
			goto yy76;
		}
	}
}


parseSetList_end:
	return YYCURSOR;
}

YYCTYPE *GPRE2C::parseTagList(YYCTYPE *input, Set *set) {
	marker = YYCURSOR;

parseTagList_start:

{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if(yych <= '\'') {
		if(yych <= 0x0000000C) {
			if(yych <= 0x00000009) {
				if(yych <= 0x00000000) goto yy82;
				if(yych <= 0x00000008) goto yy86;
				goto yy97;
			} else {
				if(yych == 0x0000000B) goto yy97;
				goto yy84;
			}
		} else {
			if(yych <= ' ') {
				if(yych <= 0x0000000D) goto yy97;
				if(yych <= 0x0000001B) goto yy86;
				goto yy97;
			} else {
				if(yych == '#') goto yy93;
				goto yy86;
			}
		}
	} else {
		if(yych <= '\\') {
			if(yych <= ':') {
				if(yych <= '(') goto yy89;
				if(yych <= ')') goto yy91;
				goto yy86;
			} else {
				if(yych <= ';') goto yy95;
				if(yych <= '[') goto yy86;
				goto yy88;
			}
		} else {
			if(yych <= 0x00002027) {
				if(yych == 0x00000085) goto yy84;
				goto yy86;
			} else {
				if(yych <= 0x00002029) goto yy84;
				if(yych <= 0x0000FFFF) goto yy86;
			}
		}
	}
yy82:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy100;
			if(yych >= 0x0000000E) goto yy100;
		} else {
			if(yych <= ' ') goto yy83;
			if(yych != '#') goto yy100;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy83;
			if(yych != ';') goto yy100;
		} else {
			if(yych <= 0x00000085) goto yy83;
			if(yych <= 0x00002027) goto yy100;
			if(yych >= 0x0000202A) goto yy100;
		}
	}
yy83:
	{goto parseTagList_end;}
yy84:
	++YYCURSOR;
	{
		marker = YYCURSOR;
		result->lines++;
		goto parseTagList_start;
		}
yy86:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy100;
yy87:
	{
		size_t length = (YYCURSOR - marker)+1;
		YYCTYPE *buffer = new YYCTYPE[length];
		buffer[length-1] = 0;
		u_strncpy(buffer, marker, (int32_t)length-1);
		CG3::CompositeTag *ctag = result->allocateCompositeTag();
		CG3::Tag *tag = result->allocateTag(buffer);
		result->addTagToCompositeTag(tag, ctag);
		result->addCompositeTagToSet(set, ctag);
		delete buffer;
		marker = YYCURSOR;
		goto parseTagList_start;
		}
yy88:
	yych = *++YYCURSOR;
	if(yych <= '\'') {
		if(yych == '#') goto yy99;
		goto yy100;
	} else {
		if(yych <= ')') goto yy99;
		if(yych == ';') goto yy99;
		goto yy100;
	}
yy89:
	++YYCURSOR;
	{
		YYCURSOR = parseCompositeTag(YYCURSOR, set);
		marker = YYCURSOR;
		goto parseTagList_start;
		}
yy91:
	++YYCURSOR;
	{u_fprintf(ux_stderr, "Error: Mismatched ) on line %u!\n", result->lines); exit(1);}
yy93:
	++YYCURSOR;
	{
		YYCURSOR = skipline(YYCURSOR);
		marker = YYCURSOR;
		goto parseTagList_start;
		}
yy95:
	++YYCURSOR;
	{goto parseTagList_end;}
yy97:
	++YYCURSOR;
	{
		marker = YYCURSOR;
		goto parseTagList_start;
		}
yy99:
	++YYCURSOR;
	yych = *YYCURSOR;
yy100:
	if(yych <= ')') {
		if(yych <= ' ') {
			if(yych <= 0x00000008) goto yy99;
			if(yych <= 0x0000000D) goto yy87;
			if(yych <= 0x0000001B) goto yy99;
			goto yy87;
		} else {
			if(yych == '#') goto yy87;
			if(yych <= '\'') goto yy99;
			goto yy87;
		}
	} else {
		if(yych <= '\\') {
			if(yych == ';') goto yy87;
			if(yych <= '[') goto yy99;
		} else {
			if(yych <= 0x00000085) {
				if(yych <= 0x00000084) goto yy99;
				goto yy87;
			} else {
				if(yych <= 0x00002027) goto yy99;
				if(yych <= 0x00002029) goto yy87;
				goto yy99;
			}
		}
	}
yy101:
	++YYCURSOR;
	yych = *YYCURSOR;
	if(yych <= '[') {
		if(yych <= 0x0000000D) {
			if(yych <= 0x00000008) goto yy99;
			goto yy87;
		} else {
			if(yych <= 0x0000001B) goto yy99;
			if(yych <= ' ') goto yy87;
			goto yy99;
		}
	} else {
		if(yych <= 0x00000085) {
			if(yych <= '\\') goto yy101;
			if(yych <= 0x00000084) goto yy99;
			goto yy87;
		} else {
			if(yych <= 0x00002027) goto yy99;
			if(yych <= 0x00002029) goto yy87;
			goto yy99;
		}
	}
}


parseTagList_end:
	return YYCURSOR;
}

YYCTYPE *GPRE2C::parseDelimiters(YYCTYPE *input, STRINGS which) {
	CG3::Set *curset = result->allocateSet();
	curset->setName(stringbits[which]);
	curset->line = result->lines;

parseDelimiters_start:

{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if(yych <= ':') {
		if(yych <= 0x0000000B) {
			if(yych <= 0x00000000) goto yy105;
			if(yych == 0x0000000A) goto yy107;
			goto yy115;
		} else {
			if(yych <= 0x0000000C) goto yy107;
			if(yych == '#') goto yy111;
			goto yy115;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ';') goto yy113;
			if(yych == '=') goto yy109;
			goto yy115;
		} else {
			if(yych <= 0x00002027) {
				if(yych <= 0x00000085) goto yy107;
				goto yy115;
			} else {
				if(yych <= 0x00002029) goto yy107;
				if(yych <= 0x0000FFFF) goto yy115;
			}
		}
	}
yy105:
	++YYCURSOR;
	{goto parseDelimiters_end;}
yy107:
	++YYCURSOR;
	{result->lines++; goto parseDelimiters_start;}
yy109:
	++YYCURSOR;
	{YYCURSOR = parseTagList(YYCURSOR, curset); goto parseDelimiters_end;}
yy111:
	++YYCURSOR;
	{YYCURSOR = skipline(YYCURSOR); goto parseDelimiters_start;}
yy113:
	++YYCURSOR;
	{goto parseDelimiters_end;}
yy115:
	++YYCURSOR;
	{goto parseDelimiters_start;}
}


parseDelimiters_end:
	result->addSet(curset);
	if (which == S_DELIMITSET) {
		result->delimiters = curset;
	}
	else if (which == S_SOFTDELIMITSET) {
		result->soft_delimiters = curset;
	}
	return YYCURSOR;
}

YYCTYPE *GPRE2C::parseMappingPrefix(YYCTYPE *input) {
parseMappingPrefix_start:

{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if(yych <= ':') {
		if(yych <= 0x0000000B) {
			if(yych <= 0x00000000) goto yy119;
			if(yych == 0x0000000A) goto yy121;
			goto yy129;
		} else {
			if(yych <= 0x0000000C) goto yy121;
			if(yych == '#') goto yy125;
			goto yy129;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ';') goto yy127;
			if(yych == '=') goto yy123;
			goto yy129;
		} else {
			if(yych <= 0x00002027) {
				if(yych <= 0x00000085) goto yy121;
				goto yy129;
			} else {
				if(yych <= 0x00002029) goto yy121;
				if(yych <= 0x0000FFFF) goto yy129;
			}
		}
	}
yy119:
	++YYCURSOR;
	{goto parseMappingPrefix_end;}
yy121:
	++YYCURSOR;
	{result->lines++; goto parseMappingPrefix_start;}
yy123:
	++YYCURSOR;
	{marker = YYCURSOR; goto parseMappingPrefix_middle;}
yy125:
	++YYCURSOR;
	{YYCURSOR = skipline(YYCURSOR); goto parseMappingPrefix_start;}
yy127:
	++YYCURSOR;
	{goto parseMappingPrefix_end;}
yy129:
	++YYCURSOR;
	{goto parseMappingPrefix_start;}
}


parseMappingPrefix_middle:

{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if(yych <= '#') {
		if(yych <= 0x0000000B) {
			if(yych <= 0x00000008) {
				if(yych >= 0x00000001) goto yy137;
			} else {
				if(yych == 0x0000000A) goto yy135;
				goto yy144;
			}
		} else {
			if(yych <= 0x0000001B) {
				if(yych <= 0x0000000C) goto yy135;
				if(yych <= 0x0000000D) goto yy144;
				goto yy137;
			} else {
				if(yych <= ' ') goto yy144;
				if(yych <= '"') goto yy137;
				goto yy140;
			}
		}
	} else {
		if(yych <= '\\') {
			if(yych <= ':') {
				if(yych <= '\'') goto yy137;
				if(yych <= ')') goto yy144;
				goto yy137;
			} else {
				if(yych <= ';') goto yy142;
				if(yych <= '[') goto yy137;
				goto yy139;
			}
		} else {
			if(yych <= 0x00002027) {
				if(yych == 0x00000085) goto yy135;
				goto yy137;
			} else {
				if(yych <= 0x00002029) goto yy135;
				if(yych <= 0x0000FFFF) goto yy137;
			}
		}
	}
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy147;
			if(yych >= 0x0000000E) goto yy147;
		} else {
			if(yych <= ' ') goto yy134;
			if(yych != '#') goto yy147;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy134;
			if(yych != ';') goto yy147;
		} else {
			if(yych <= 0x00000085) goto yy134;
			if(yych <= 0x00002027) goto yy147;
			if(yych >= 0x0000202A) goto yy147;
		}
	}
yy134:
	{goto parseMappingPrefix_end;}
yy135:
	++YYCURSOR;
	{result->lines++; marker = YYCURSOR; goto parseMappingPrefix_middle;}
yy137:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy147;
yy138:
	{result->mapping_prefix = marker[0]; goto parseMappingPrefix_middle;}
yy139:
	yych = *++YYCURSOR;
	if(yych <= '\'') {
		if(yych == '#') goto yy146;
		goto yy147;
	} else {
		if(yych <= ')') goto yy146;
		if(yych == ';') goto yy146;
		goto yy147;
	}
yy140:
	++YYCURSOR;
	{YYCURSOR = skipline(YYCURSOR); marker = YYCURSOR; goto parseMappingPrefix_middle;}
yy142:
	++YYCURSOR;
	{goto parseMappingPrefix_end;}
yy144:
	++YYCURSOR;
	{marker = YYCURSOR; goto parseMappingPrefix_middle;}
yy146:
	++YYCURSOR;
	yych = *YYCURSOR;
yy147:
	if(yych <= ')') {
		if(yych <= ' ') {
			if(yych <= 0x00000008) goto yy146;
			if(yych <= 0x0000000D) goto yy138;
			if(yych <= 0x0000001B) goto yy146;
			goto yy138;
		} else {
			if(yych == '#') goto yy138;
			if(yych <= '\'') goto yy146;
			goto yy138;
		}
	} else {
		if(yych <= '\\') {
			if(yych == ';') goto yy138;
			if(yych <= '[') goto yy146;
		} else {
			if(yych <= 0x00000085) {
				if(yych <= 0x00000084) goto yy146;
				goto yy138;
			} else {
				if(yych <= 0x00002027) goto yy146;
				if(yych <= 0x00002029) goto yy138;
				goto yy146;
			}
		}
	}
yy148:
	++YYCURSOR;
	yych = *YYCURSOR;
	if(yych <= '[') {
		if(yych <= 0x0000000D) {
			if(yych <= 0x00000008) goto yy146;
			goto yy138;
		} else {
			if(yych <= 0x0000001B) goto yy146;
			if(yych <= ' ') goto yy138;
			goto yy146;
		}
	} else {
		if(yych <= 0x00000085) {
			if(yych <= '\\') goto yy148;
			if(yych <= 0x00000084) goto yy146;
			goto yy138;
		} else {
			if(yych <= 0x00002027) goto yy146;
			if(yych <= 0x00002029) goto yy138;
			goto yy146;
		}
	}
}

parseMappingPrefix_end:
	return YYCURSOR;
}

YYCTYPE *GPRE2C::parseList(YYCTYPE *input) {
	marker = YYCURSOR;
	CG3::Set *curset = result->allocateSet();
	curset->line = result->lines;

parseList_start:

{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if(yych <= '\'') {
		if(yych <= 0x0000000C) {
			if(yych <= 0x00000009) {
				if(yych <= 0x00000000) goto yy152;
				if(yych <= 0x00000008) goto yy160;
				goto yy165;
			} else {
				if(yych == 0x0000000B) goto yy165;
				goto yy154;
			}
		} else {
			if(yych <= ' ') {
				if(yych <= 0x0000000D) goto yy165;
				if(yych <= 0x0000001B) goto yy160;
				goto yy165;
			} else {
				if(yych == '#') goto yy158;
				goto yy160;
			}
		}
	} else {
		if(yych <= '[') {
			if(yych <= ';') {
				if(yych <= ')') goto yy165;
				if(yych <= ':') goto yy160;
				goto yy163;
			} else {
				if(yych == '=') goto yy156;
				goto yy160;
			}
		} else {
			if(yych <= 0x00000085) {
				if(yych <= '\\') goto yy162;
				if(yych <= 0x00000084) goto yy160;
				goto yy154;
			} else {
				if(yych <= 0x00002027) goto yy160;
				if(yych <= 0x00002029) goto yy154;
				if(yych <= 0x0000FFFF) goto yy160;
			}
		}
	}
yy152:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ')') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy168;
			if(yych >= 0x0000000E) goto yy168;
		} else {
			if(yych <= ' ') goto yy153;
			if(yych <= '\'') goto yy168;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych != ';') goto yy168;
		} else {
			if(yych <= 0x00000085) goto yy153;
			if(yych <= 0x00002027) goto yy168;
			if(yych >= 0x0000202A) goto yy168;
		}
	}
yy153:
	{goto parseList_end;}
yy154:
	++YYCURSOR;
	{marker = YYCURSOR; result->lines++; goto parseList_start;}
yy156:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ')') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy168;
			if(yych >= 0x0000000E) goto yy168;
		} else {
			if(yych <= ' ') goto yy157;
			if(yych <= '\'') goto yy168;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych != ';') goto yy168;
		} else {
			if(yych <= 0x00000085) goto yy157;
			if(yych <= 0x00002027) goto yy168;
			if(yych >= 0x0000202A) goto yy168;
		}
	}
yy157:
	{YYCURSOR = parseTagList(YYCURSOR, curset); marker = YYCURSOR; goto parseList_end;}
yy158:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ')') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy168;
			if(yych >= 0x0000000E) goto yy168;
		} else {
			if(yych <= ' ') goto yy159;
			if(yych <= '\'') goto yy168;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych != ';') goto yy168;
		} else {
			if(yych <= 0x00000085) goto yy159;
			if(yych <= 0x00002027) goto yy168;
			if(yych >= 0x0000202A) goto yy168;
		}
	}
yy159:
	{YYCURSOR = skipline(YYCURSOR); marker = YYCURSOR; goto parseList_start;}
yy160:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy168;
yy161:
	{
		size_t length = (YYCURSOR - marker)+1;
		YYCTYPE *buffer = new YYCTYPE[length];
		buffer[length-1] = 0;
		u_strncpy(buffer, marker, (int32_t)length-1);
		curset->setName(buffer);
		delete buffer;
		marker = YYCURSOR;
		goto parseList_start;
		}
yy162:
	yych = *++YYCURSOR;
	if(yych <= '\'') goto yy168;
	if(yych <= ')') goto yy167;
	if(yych == ';') goto yy167;
	goto yy168;
yy163:
	++YYCURSOR;
	{goto parseList_end;}
yy165:
	++YYCURSOR;
	{marker = YYCURSOR; goto parseList_start;}
yy167:
	++YYCURSOR;
	yych = *YYCURSOR;
yy168:
	if(yych <= ':') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy167;
			if(yych <= 0x0000000D) goto yy161;
			goto yy167;
		} else {
			if(yych <= ' ') goto yy161;
			if(yych <= '\'') goto yy167;
			if(yych <= ')') goto yy161;
			goto yy167;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ';') goto yy161;
			if(yych != '\\') goto yy167;
		} else {
			if(yych <= 0x00000085) goto yy161;
			if(yych <= 0x00002027) goto yy167;
			if(yych <= 0x00002029) goto yy161;
			goto yy167;
		}
	}
yy169:
	++YYCURSOR;
	yych = *YYCURSOR;
	if(yych <= '[') {
		if(yych <= 0x0000000D) {
			if(yych <= 0x00000008) goto yy167;
			goto yy161;
		} else {
			if(yych <= 0x0000001B) goto yy167;
			if(yych <= ' ') goto yy161;
			goto yy167;
		}
	} else {
		if(yych <= 0x00000085) {
			if(yych <= '\\') goto yy169;
			if(yych <= 0x00000084) goto yy167;
			goto yy161;
		} else {
			if(yych <= 0x00002027) goto yy167;
			if(yych <= 0x00002029) goto yy161;
			goto yy167;
		}
	}
}


parseList_end:
	result->addSet(curset);
	return YYCURSOR;
}

YYCTYPE *GPRE2C::parseSet(YYCTYPE *input) {
	marker = YYCURSOR;
	CG3::Set *curset = result->allocateSet();
	curset->line = result->lines;
	if (result->lines == 1333) {
		input=input;
	}

parseSet_start:

{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if(yych <= '\'') {
		if(yych <= 0x0000000C) {
			if(yych <= 0x00000009) {
				if(yych <= 0x00000000) goto yy173;
				if(yych <= 0x00000008) goto yy181;
				goto yy186;
			} else {
				if(yych == 0x0000000B) goto yy186;
				goto yy175;
			}
		} else {
			if(yych <= ' ') {
				if(yych <= 0x0000000D) goto yy186;
				if(yych <= 0x0000001B) goto yy181;
				goto yy186;
			} else {
				if(yych == '#') goto yy179;
				goto yy181;
			}
		}
	} else {
		if(yych <= '[') {
			if(yych <= ';') {
				if(yych <= ')') goto yy186;
				if(yych <= ':') goto yy181;
				goto yy184;
			} else {
				if(yych == '=') goto yy177;
				goto yy181;
			}
		} else {
			if(yych <= 0x00000085) {
				if(yych <= '\\') goto yy183;
				if(yych <= 0x00000084) goto yy181;
				goto yy175;
			} else {
				if(yych <= 0x00002027) goto yy181;
				if(yych <= 0x00002029) goto yy175;
				if(yych <= 0x0000FFFF) goto yy181;
			}
		}
	}
yy173:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ')') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy189;
			if(yych >= 0x0000000E) goto yy189;
		} else {
			if(yych <= ' ') goto yy174;
			if(yych <= '\'') goto yy189;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych != ';') goto yy189;
		} else {
			if(yych <= 0x00000085) goto yy174;
			if(yych <= 0x00002027) goto yy189;
			if(yych >= 0x0000202A) goto yy189;
		}
	}
yy174:
	{goto parseSet_end;}
yy175:
	++YYCURSOR;
	{marker = YYCURSOR; result->lines++; goto parseSet_start;}
yy177:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ')') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy189;
			if(yych >= 0x0000000E) goto yy189;
		} else {
			if(yych <= ' ') goto yy178;
			if(yych <= '\'') goto yy189;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych != ';') goto yy189;
		} else {
			if(yych <= 0x00000085) goto yy178;
			if(yych <= 0x00002027) goto yy189;
			if(yych >= 0x0000202A) goto yy189;
		}
	}
yy178:
	{YYCURSOR = parseSetList(YYCURSOR, curset); marker = YYCURSOR; goto parseSet_end;}
yy179:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ')') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy189;
			if(yych >= 0x0000000E) goto yy189;
		} else {
			if(yych <= ' ') goto yy180;
			if(yych <= '\'') goto yy189;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych != ';') goto yy189;
		} else {
			if(yych <= 0x00000085) goto yy180;
			if(yych <= 0x00002027) goto yy189;
			if(yych >= 0x0000202A) goto yy189;
		}
	}
yy180:
	{YYCURSOR = skipline(YYCURSOR); marker = YYCURSOR; goto parseSet_start;}
yy181:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy189;
yy182:
	{
		size_t length = (YYCURSOR - marker)+1;
		YYCTYPE *buffer = new YYCTYPE[length];
		buffer[length-1] = 0;
		u_strncpy(buffer, marker, (int32_t)length-1);
		curset->setName(buffer);
		delete buffer;
		marker = YYCURSOR;
		goto parseSet_start;
		}
yy183:
	yych = *++YYCURSOR;
	if(yych <= '\'') goto yy189;
	if(yych <= ')') goto yy188;
	if(yych == ';') goto yy188;
	goto yy189;
yy184:
	++YYCURSOR;
	{goto parseSet_end;}
yy186:
	++YYCURSOR;
	{marker = YYCURSOR; goto parseSet_start;}
yy188:
	++YYCURSOR;
	yych = *YYCURSOR;
yy189:
	if(yych <= ':') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy188;
			if(yych <= 0x0000000D) goto yy182;
			goto yy188;
		} else {
			if(yych <= ' ') goto yy182;
			if(yych <= '\'') goto yy188;
			if(yych <= ')') goto yy182;
			goto yy188;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ';') goto yy182;
			if(yych != '\\') goto yy188;
		} else {
			if(yych <= 0x00000085) goto yy182;
			if(yych <= 0x00002027) goto yy188;
			if(yych <= 0x00002029) goto yy182;
			goto yy188;
		}
	}
yy190:
	++YYCURSOR;
	yych = *YYCURSOR;
	if(yych <= '[') {
		if(yych <= 0x0000000D) {
			if(yych <= 0x00000008) goto yy188;
			goto yy182;
		} else {
			if(yych <= 0x0000001B) goto yy188;
			if(yych <= ' ') goto yy182;
			goto yy188;
		}
	} else {
		if(yych <= 0x00000085) {
			if(yych <= '\\') goto yy190;
			if(yych <= 0x00000084) goto yy188;
			goto yy182;
		} else {
			if(yych <= 0x00002027) goto yy188;
			if(yych <= 0x00002029) goto yy182;
			goto yy188;
		}
	}
}


parseSet_end:
	if (curset->sets.size() == 1) {
		uint32_t res = curset->sets.at(0);
		result->set_alias[hash_sdbm_uchar(curset->name, 0)] = res;
		result->destroySet(curset);
		curset = result->getSet(res);
	}
	result->addSet(curset);
	return YYCURSOR;
}

YYCTYPE *GPRE2C::parsePreferredTargets(YYCTYPE *input) {
	marker = YYCURSOR;

parsePreferredTargets_start:

{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if(yych <= '\'') {
		if(yych <= 0x0000000C) {
			if(yych <= 0x00000009) {
				if(yych <= 0x00000000) goto yy194;
				if(yych <= 0x00000008) goto yy198;
				goto yy209;
			} else {
				if(yych == 0x0000000B) goto yy209;
				goto yy196;
			}
		} else {
			if(yych <= ' ') {
				if(yych <= 0x0000000D) goto yy209;
				if(yych <= 0x0000001B) goto yy198;
				goto yy209;
			} else {
				if(yych == '#') goto yy205;
				goto yy198;
			}
		}
	} else {
		if(yych <= '\\') {
			if(yych <= ':') {
				if(yych <= '(') goto yy201;
				if(yych <= ')') goto yy203;
				goto yy198;
			} else {
				if(yych <= ';') goto yy207;
				if(yych <= '[') goto yy198;
				goto yy200;
			}
		} else {
			if(yych <= 0x00002027) {
				if(yych == 0x00000085) goto yy196;
				goto yy198;
			} else {
				if(yych <= 0x00002029) goto yy196;
				if(yych <= 0x0000FFFF) goto yy198;
			}
		}
	}
yy194:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy212;
			if(yych >= 0x0000000E) goto yy212;
		} else {
			if(yych <= ' ') goto yy195;
			if(yych != '#') goto yy212;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy195;
			if(yych != ';') goto yy212;
		} else {
			if(yych <= 0x00000085) goto yy195;
			if(yych <= 0x00002027) goto yy212;
			if(yych >= 0x0000202A) goto yy212;
		}
	}
yy195:
	{goto parsePreferredTargets_end;}
yy196:
	++YYCURSOR;
	{
		marker = YYCURSOR;
		result->lines++;
		goto parsePreferredTargets_start;
		}
yy198:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy212;
yy199:
	{
		size_t length = (YYCURSOR - marker)+1;
		YYCTYPE *buffer = new YYCTYPE[length];
		buffer[length-1] = 0;
		u_strncpy(buffer, marker, (int32_t)length-1);
		if (!(buffer[0] == '=' && u_strlen(buffer) == 1)) {
			result->addPreferredTarget(buffer);
		}
		delete buffer;
		marker = YYCURSOR;
		goto parsePreferredTargets_start;
		}
yy200:
	yych = *++YYCURSOR;
	if(yych <= '\'') {
		if(yych == '#') goto yy211;
		goto yy212;
	} else {
		if(yych <= ')') goto yy211;
		if(yych == ';') goto yy211;
		goto yy212;
	}
yy201:
	++YYCURSOR;
	{u_fprintf(ux_stderr, "Error: Unexpected ( on line %u!\n", result->lines); exit(1);}
yy203:
	++YYCURSOR;
	{u_fprintf(ux_stderr, "Error: Unexpected ) on line %u!\n", result->lines); exit(1);}
yy205:
	++YYCURSOR;
	{
		YYCURSOR = skipline(YYCURSOR);
		marker = YYCURSOR;
		goto parsePreferredTargets_start;
		}
yy207:
	++YYCURSOR;
	{goto parsePreferredTargets_end;}
yy209:
	++YYCURSOR;
	{
		marker = YYCURSOR;
		goto parsePreferredTargets_start;
		}
yy211:
	++YYCURSOR;
	yych = *YYCURSOR;
yy212:
	if(yych <= ')') {
		if(yych <= ' ') {
			if(yych <= 0x00000008) goto yy211;
			if(yych <= 0x0000000D) goto yy199;
			if(yych <= 0x0000001B) goto yy211;
			goto yy199;
		} else {
			if(yych == '#') goto yy199;
			if(yych <= '\'') goto yy211;
			goto yy199;
		}
	} else {
		if(yych <= '\\') {
			if(yych == ';') goto yy199;
			if(yych <= '[') goto yy211;
		} else {
			if(yych <= 0x00000085) {
				if(yych <= 0x00000084) goto yy211;
				goto yy199;
			} else {
				if(yych <= 0x00002027) goto yy211;
				if(yych <= 0x00002029) goto yy199;
				goto yy211;
			}
		}
	}
yy213:
	++YYCURSOR;
	yych = *YYCURSOR;
	if(yych <= '[') {
		if(yych <= 0x0000000D) {
			if(yych <= 0x00000008) goto yy211;
			goto yy199;
		} else {
			if(yych <= 0x0000001B) goto yy211;
			if(yych <= ' ') goto yy199;
			goto yy211;
		}
	} else {
		if(yych <= 0x00000085) {
			if(yych <= '\\') goto yy213;
			if(yych <= 0x00000084) goto yy211;
			goto yy199;
		} else {
			if(yych <= 0x00002027) goto yy211;
			if(yych <= 0x00002029) goto yy199;
			goto yy211;
		}
	}
}


parsePreferredTargets_end:
	if (result->preferred_targets.empty()) {
		u_fprintf(ux_stderr, "Warning: PREFERRED-TARGETS was declared with no elements on line %u.\n", result->lines);
	}
	return YYCURSOR;
}

KEYWORDS GPRE2C::scan(YYCTYPE *input) {
	KEYWORDS retval = K_IGNORE;
	YYCTYPE *YYMARKER = 0;
	YYMARKER = YYMARKER; // Just to foil the warning. Compiler will optimize this away.
	marker = YYCURSOR;
	
scan_start:

{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if(yych <= 'O') {
		if(yych <= ':') {
			if(yych <= 0x0000000D) {
				if(yych <= 0x00000009) {
					if(yych <= 0x00000000) goto yy217;
					if(yych <= 0x00000008) goto yy238;
					goto yy221;
				} else {
					if(yych == 0x0000000B) goto yy221;
					if(yych <= 0x0000000C) goto yy219;
					goto yy221;
				}
			} else {
				if(yych <= '"') {
					if(yych <= 0x0000001B) goto yy238;
					if(yych <= ' ') goto yy221;
					goto yy238;
				} else {
					if(yych <= '#') goto yy236;
					if(yych <= '\'') goto yy238;
					if(yych <= ')') goto yy240;
					goto yy238;
				}
			}
		} else {
			if(yych <= 'E') {
				if(yych <= 'A') {
					if(yych <= ';') goto yy240;
					if(yych <= '@') goto yy238;
					goto yy227;
				} else {
					if(yych <= 'B') goto yy225;
					if(yych <= 'C') goto yy230;
					if(yych <= 'D') goto yy231;
					goto yy232;
				}
			} else {
				if(yych <= 'J') {
					if(yych <= 'H') goto yy238;
					if(yych <= 'I') goto yy235;
					goto yy233;
				} else {
					if(yych <= 'K') goto yy238;
					if(yych <= 'L') goto yy234;
					if(yych <= 'M') goto yy228;
					goto yy238;
				}
			}
		}
	} else {
		if(yych <= 'i') {
			if(yych <= '`') {
				if(yych <= 'R') {
					if(yych <= 'P') goto yy223;
					if(yych <= 'Q') goto yy238;
					goto yy229;
				} else {
					if(yych <= 'S') goto yy226;
					if(yych == '\\') goto yy239;
					goto yy238;
				}
			} else {
				if(yych <= 'c') {
					if(yych <= 'a') goto yy227;
					if(yych <= 'b') goto yy225;
					goto yy230;
				} else {
					if(yych <= 'd') goto yy231;
					if(yych <= 'e') goto yy232;
					if(yych <= 'h') goto yy238;
					goto yy235;
				}
			}
		} else {
			if(yych <= 'q') {
				if(yych <= 'l') {
					if(yych <= 'j') goto yy233;
					if(yych <= 'k') goto yy238;
					goto yy234;
				} else {
					if(yych <= 'm') goto yy228;
					if(yych == 'p') goto yy223;
					goto yy238;
				}
			} else {
				if(yych <= 0x00000085) {
					if(yych <= 'r') goto yy229;
					if(yych <= 's') goto yy226;
					if(yych <= 0x00000084) goto yy238;
					goto yy219;
				} else {
					if(yych <= 0x00002027) goto yy238;
					if(yych <= 0x00002029) goto yy219;
					if(yych <= 0x0000FFFF) goto yy238;
				}
			}
		}
	}
yy217:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy218;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy218;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy218;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy218:
	{retval = K_IGNORE; goto scan_end;}
yy219:
	++YYCURSOR;
	{marker = YYCURSOR; result->lines++; goto scan_start;}
yy221:
	++YYCURSOR;
	{goto scan_start;}
yy223:
	++YYCURSOR;
	if((yych = *YYCURSOR) == 'R') goto yy440;
	if(yych == 'r') goto yy440;
	goto yy243;
yy224:
	{goto scan_start;}
yy225:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy425;
	if(yych == 'e') goto yy425;
	goto yy243;
yy226:
	yych = *++YYCURSOR;
	if(yych <= 'U') {
		if(yych <= 'N') {
			if(yych == 'E') goto yy375;
			goto yy243;
		} else {
			if(yych <= 'O') goto yy376;
			if(yych <= 'T') goto yy243;
			goto yy377;
		}
	} else {
		if(yych <= 'n') {
			if(yych == 'e') goto yy375;
			goto yy243;
		} else {
			if(yych <= 'o') goto yy376;
			if(yych == 'u') goto yy377;
			goto yy243;
		}
	}
yy227:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'B':
	case 'b':	goto yy341;
	case 'D':
	case 'd':	goto yy342;
	case 'F':
	case 'f':	goto yy343;
	case 'N':
	case 'n':	goto yy344;
	case 'P':
	case 'p':	goto yy345;
	default:	goto yy243;
	}
yy228:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy320;
	if(yych == 'a') goto yy320;
	goto yy243;
yy229:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy299;
	if(yych == 'e') goto yy299;
	goto yy243;
yy230:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy278;
	if(yych == 'o') goto yy278;
	goto yy243;
yy231:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy267;
	if(yych == 'e') goto yy267;
	goto yy243;
yy232:
	yych = *++YYCURSOR;
	if(yych <= 'X') {
		if(yych == 'N') goto yy257;
		if(yych <= 'W') goto yy243;
		goto yy258;
	} else {
		if(yych <= 'n') {
			if(yych <= 'm') goto yy243;
			goto yy257;
		} else {
			if(yych == 'x') goto yy258;
			goto yy243;
		}
	}
yy233:
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy253;
	if(yych == 'u') goto yy253;
	goto yy243;
yy234:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy249;
	if(yych == 'i') goto yy249;
	goto yy243;
yy235:
	yych = *++YYCURSOR;
	if(yych == 'F') goto yy246;
	if(yych == 'f') goto yy246;
	goto yy243;
yy236:
	++YYCURSOR;
	{YYCURSOR = skipline(YYCURSOR); marker = YYCURSOR; goto scan_start;}
yy238:
	yych = *++YYCURSOR;
	goto yy243;
yy239:
	yych = *++YYCURSOR;
	if(yych <= '\'') {
		if(yych == '#') goto yy242;
		goto yy243;
	} else {
		if(yych <= ')') goto yy242;
		if(yych == ';') goto yy242;
		goto yy243;
	}
yy240:
	++YYCURSOR;
	{u_fprintf(ux_stderr, "Error: Unexpected input on line %u!\n", result->lines); goto scan_end;}
yy242:
	++YYCURSOR;
	yych = *YYCURSOR;
yy243:
	if(yych <= ')') {
		if(yych <= ' ') {
			if(yych <= 0x00000008) goto yy242;
			if(yych <= 0x0000000D) goto yy224;
			if(yych <= 0x0000001B) goto yy242;
			goto yy224;
		} else {
			if(yych == '#') goto yy224;
			if(yych <= '\'') goto yy242;
			goto yy224;
		}
	} else {
		if(yych <= '\\') {
			if(yych == ';') goto yy224;
			if(yych <= '[') goto yy242;
		} else {
			if(yych <= 0x00000085) {
				if(yych <= 0x00000084) goto yy242;
				goto yy224;
			} else {
				if(yych <= 0x00002027) goto yy242;
				if(yych <= 0x00002029) goto yy224;
				goto yy242;
			}
		}
	}
yy244:
	++YYCURSOR;
	yych = *YYCURSOR;
	if(yych <= '[') {
		if(yych <= 0x0000000D) {
			if(yych <= 0x00000008) goto yy242;
			goto yy224;
		} else {
			if(yych <= 0x0000001B) goto yy242;
			if(yych <= ' ') goto yy224;
			goto yy242;
		}
	} else {
		if(yych <= 0x00000085) {
			if(yych <= '\\') goto yy244;
			if(yych <= 0x00000084) goto yy242;
			goto yy224;
		} else {
			if(yych <= 0x00002027) goto yy242;
			if(yych <= 0x00002029) goto yy224;
			goto yy242;
		}
	}
yy246:
	yych = *++YYCURSOR;
	if(yych == 'F') goto yy247;
	if(yych != 'f') goto yy243;
yy247:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy248;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy248;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy248;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy248:
	{goto scan_start;}
yy249:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy250;
	if(yych != 's') goto yy243;
yy250:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy251;
	if(yych != 't') goto yy243;
yy251:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy252;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy252;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy252;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy252:
	{YYCURSOR = parseList(YYCURSOR); marker = YYCURSOR; goto scan_start;}
yy253:
	yych = *++YYCURSOR;
	if(yych == 'M') goto yy254;
	if(yych != 'm') goto yy243;
yy254:
	yych = *++YYCURSOR;
	if(yych == 'P') goto yy255;
	if(yych != 'p') goto yy243;
yy255:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy256;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy256;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy256;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy256:
	{goto scan_start;}
yy257:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy265;
	if(yych == 'd') goto yy265;
	goto yy243;
yy258:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy259;
	if(yych != 'e') goto yy243;
yy259:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy260;
	if(yych != 'c') goto yy243;
yy260:
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy261;
	if(yych != 'u') goto yy243;
yy261:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy262;
	if(yych != 't') goto yy243;
yy262:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy263;
	if(yych != 'e') goto yy243;
yy263:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy264;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy264;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy264;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy264:
	{goto scan_start;}
yy265:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy266;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy266;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy266;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy266:
	{retval = K_IGNORE; goto scan_end;}
yy267:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy268;
	if(yych != 'l') goto yy243;
yy268:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy269;
	if(yych != 'i') goto yy243;
yy269:
	yych = *++YYCURSOR;
	if(yych == 'M') goto yy270;
	if(yych != 'm') goto yy243;
yy270:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy271;
	if(yych != 'i') goto yy243;
yy271:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy272;
	if(yych != 't') goto yy243;
yy272:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ':') {
		if(yych <= ' ') {
			if(yych <= 0x00000008) goto yy243;
			if(yych <= 0x0000000D) goto yy273;
			if(yych <= 0x0000001B) goto yy243;
		} else {
			if(yych <= '#') {
				if(yych <= '"') goto yy243;
			} else {
				if(yych <= '\'') goto yy243;
				if(yych >= '*') goto yy243;
			}
		}
	} else {
		if(yych <= 'e') {
			if(yych <= 'D') {
				if(yych >= '<') goto yy243;
			} else {
				if(yych <= 'E') goto yy274;
				if(yych <= 'd') goto yy243;
				goto yy274;
			}
		} else {
			if(yych <= 0x00000085) {
				if(yych <= 0x00000084) goto yy243;
			} else {
				if(yych <= 0x00002027) goto yy243;
				if(yych >= 0x0000202A) goto yy243;
			}
		}
	}
yy273:
	{goto scan_start;}
yy274:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy275;
	if(yych != 'r') goto yy243;
yy275:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy276;
	if(yych != 's') goto yy243;
yy276:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy277;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy277;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy277;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy277:
	{YYCURSOR = parseDelimiters(YYCURSOR, S_DELIMITSET); marker = YYCURSOR; goto scan_start;}
yy278:
	yych = *++YYCURSOR;
	if(yych <= 'R') {
		if(yych == 'N') goto yy280;
		if(yych <= 'Q') goto yy243;
	} else {
		if(yych <= 'n') {
			if(yych <= 'm') goto yy243;
			goto yy280;
		} else {
			if(yych != 'r') goto yy243;
		}
	}
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy290;
	if(yych == 'r') goto yy290;
	goto yy243;
yy280:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy281;
	if(yych != 's') goto yy243;
yy281:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy282;
	if(yych != 't') goto yy243;
yy282:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy283;
	if(yych != 'r') goto yy243;
yy283:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy284;
	if(yych != 'a') goto yy243;
yy284:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy285;
	if(yych != 'i') goto yy243;
yy285:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy286;
	if(yych != 'n') goto yy243;
yy286:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy287;
	if(yych != 't') goto yy243;
yy287:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy288;
	if(yych != 's') goto yy243;
yy288:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy289;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy289;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy289;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy289:
	{in_section = true; in_before_sections = in_after_sections = false; goto scan_start;}
yy290:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy291;
	if(yych != 'e') goto yy243;
yy291:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy292;
	if(yych != 'c') goto yy243;
yy292:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy293;
	if(yych != 't') goto yy243;
yy293:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy294;
	if(yych != 'i') goto yy243;
yy294:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy295;
	if(yych != 'o') goto yy243;
yy295:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy296;
	if(yych != 'n') goto yy243;
yy296:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy297;
	if(yych != 's') goto yy243;
yy297:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy298;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy298;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy298;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy298:
	{in_before_sections = true; in_section = in_after_sections = false; goto scan_start;}
yy299:
	yych = *++YYCURSOR;
	if(yych <= 'P') {
		if(yych == 'M') goto yy300;
		if(yych <= 'O') goto yy243;
		goto yy301;
	} else {
		if(yych <= 'm') {
			if(yych <= 'l') goto yy243;
		} else {
			if(yych == 'p') goto yy301;
			goto yy243;
		}
	}
yy300:
	yych = *++YYCURSOR;
	if(yych <= 'V') {
		if(yych == 'O') goto yy307;
		if(yych <= 'U') goto yy243;
		goto yy308;
	} else {
		if(yych <= 'o') {
			if(yych <= 'n') goto yy243;
			goto yy307;
		} else {
			if(yych == 'v') goto yy308;
			goto yy243;
		}
	}
yy301:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy302;
	if(yych != 'l') goto yy243;
yy302:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy303;
	if(yych != 'a') goto yy243;
yy303:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy304;
	if(yych != 'c') goto yy243;
yy304:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy305;
	if(yych != 'e') goto yy243;
yy305:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy306;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy306;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy306;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy306:
	{goto scan_start;}
yy307:
	yych = *++YYCURSOR;
	if(yych == 'V') goto yy317;
	if(yych == 'v') goto yy317;
	goto yy243;
yy308:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy309;
	if(yych != 'a') goto yy243;
yy309:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy310;
	if(yych != 'r') goto yy243;
yy310:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy311;
	if(yych != 'i') goto yy243;
yy311:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy312;
	if(yych != 'a') goto yy243;
yy312:
	yych = *++YYCURSOR;
	if(yych == 'B') goto yy313;
	if(yych != 'b') goto yy243;
yy313:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy314;
	if(yych != 'l') goto yy243;
yy314:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy315;
	if(yych != 'e') goto yy243;
yy315:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy316;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy316;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy316;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy316:
	{goto scan_start;}
yy317:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy318;
	if(yych != 'e') goto yy243;
yy318:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy319;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy319;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy319;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy319:
	{goto scan_start;}
yy320:
	yych = *++YYCURSOR;
	if(yych <= 'T') {
		if(yych == 'P') goto yy321;
		if(yych <= 'S') goto yy243;
		goto yy323;
	} else {
		if(yych <= 'p') {
			if(yych <= 'o') goto yy243;
		} else {
			if(yych == 't') goto yy323;
			goto yy243;
		}
	}
yy321:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ':') {
		if(yych <= ' ') {
			if(yych <= 0x00000008) goto yy243;
			if(yych <= 0x0000000D) goto yy322;
			if(yych <= 0x0000001B) goto yy243;
		} else {
			if(yych <= '#') {
				if(yych <= '"') goto yy243;
			} else {
				if(yych <= '\'') goto yy243;
				if(yych >= '*') goto yy243;
			}
		}
	} else {
		if(yych <= 'p') {
			if(yych <= 'O') {
				if(yych >= '<') goto yy243;
			} else {
				if(yych <= 'P') goto yy327;
				if(yych <= 'o') goto yy243;
				goto yy327;
			}
		} else {
			if(yych <= 0x00000085) {
				if(yych <= 0x00000084) goto yy243;
			} else {
				if(yych <= 0x00002027) goto yy243;
				if(yych >= 0x0000202A) goto yy243;
			}
		}
	}
yy322:
	{goto scan_start;}
yy323:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy324;
	if(yych != 'c') goto yy243;
yy324:
	yych = *++YYCURSOR;
	if(yych == 'H') goto yy325;
	if(yych != 'h') goto yy243;
yy325:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy326;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy326;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy326;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy326:
	{goto scan_start;}
yy327:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy328;
	if(yych != 'i') goto yy243;
yy328:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy329;
	if(yych != 'n') goto yy243;
yy329:
	yych = *++YYCURSOR;
	if(yych == 'G') goto yy330;
	if(yych != 'g') goto yy243;
yy330:
	yych = *++YYCURSOR;
	if(yych <= 'R') {
		if(yych != '-') goto yy243;
	} else {
		if(yych <= 'S') goto yy332;
		if(yych == 's') goto yy332;
		goto yy243;
	}
	yych = *++YYCURSOR;
	if(yych == 'P') goto yy334;
	if(yych == 'p') goto yy334;
	goto yy243;
yy332:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy333;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy333;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy333;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy333:
	{in_before_sections = true; in_section = in_after_sections = false; goto scan_start;}
yy334:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy335;
	if(yych != 'r') goto yy243;
yy335:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy336;
	if(yych != 'e') goto yy243;
yy336:
	yych = *++YYCURSOR;
	if(yych == 'F') goto yy337;
	if(yych != 'f') goto yy243;
yy337:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy338;
	if(yych != 'i') goto yy243;
yy338:
	yych = *++YYCURSOR;
	if(yych == 'X') goto yy339;
	if(yych != 'x') goto yy243;
yy339:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy340;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy340;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy340;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy340:
	{YYCURSOR = parseMappingPrefix(YYCURSOR); marker = YYCURSOR; goto scan_start;}
yy341:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy371;
	if(yych == 'o') goto yy371;
	goto yy243;
yy342:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy369;
	if(yych == 'd') goto yy369;
	goto yy243;
yy343:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy356;
	if(yych == 't') goto yy356;
	goto yy243;
yy344:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy351;
	if(yych == 'c') goto yy351;
	goto yy243;
yy345:
	yych = *++YYCURSOR;
	if(yych == 'P') goto yy346;
	if(yych != 'p') goto yy243;
yy346:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy347;
	if(yych != 'e') goto yy243;
yy347:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy348;
	if(yych != 'n') goto yy243;
yy348:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy349;
	if(yych != 'd') goto yy243;
yy349:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy350;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy350;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy350;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy350:
	{goto scan_start;}
yy351:
	yych = *++YYCURSOR;
	if(yych == 'H') goto yy352;
	if(yych != 'h') goto yy243;
yy352:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy353;
	if(yych != 'o') goto yy243;
yy353:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy354;
	if(yych != 'r') goto yy243;
yy354:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy355;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy355;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy355;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy355:
	{goto scan_start;}
yy356:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy357;
	if(yych != 'e') goto yy243;
yy357:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy358;
	if(yych != 'r') goto yy243;
yy358:
	yych = *++YYCURSOR;
	if(yych != '-') goto yy243;
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy360;
	if(yych != 's') goto yy243;
yy360:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy361;
	if(yych != 'e') goto yy243;
yy361:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy362;
	if(yych != 'c') goto yy243;
yy362:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy363;
	if(yych != 't') goto yy243;
yy363:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy364;
	if(yych != 'i') goto yy243;
yy364:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy365;
	if(yych != 'o') goto yy243;
yy365:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy366;
	if(yych != 'n') goto yy243;
yy366:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy367;
	if(yych != 's') goto yy243;
yy367:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy368;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy368;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy368;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy368:
	{in_after_sections = true; in_section = in_before_sections = false; goto scan_start;}
yy369:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy370;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy370;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy370;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy370:
	{goto scan_start;}
yy371:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy372;
	if(yych != 'r') goto yy243;
yy372:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy373;
	if(yych != 't') goto yy243;
yy373:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy374;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy374;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy374;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy374:
	{goto scan_start;}
yy375:
	yych = *++YYCURSOR;
	if(yych <= 'T') {
		if(yych <= 'K') {
			if(yych == 'C') goto yy403;
			goto yy243;
		} else {
			if(yych <= 'L') goto yy404;
			if(yych <= 'S') goto yy243;
			goto yy401;
		}
	} else {
		if(yych <= 'k') {
			if(yych == 'c') goto yy403;
			goto yy243;
		} else {
			if(yych <= 'l') goto yy404;
			if(yych == 't') goto yy401;
			goto yy243;
		}
	}
yy376:
	yych = *++YYCURSOR;
	if(yych == 'F') goto yy387;
	if(yych == 'f') goto yy387;
	goto yy243;
yy377:
	yych = *++YYCURSOR;
	if(yych == 'B') goto yy378;
	if(yych != 'b') goto yy243;
yy378:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy379;
	if(yych != 's') goto yy243;
yy379:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy380;
	if(yych != 't') goto yy243;
yy380:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy381;
	if(yych != 'i') goto yy243;
yy381:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy382;
	if(yych != 't') goto yy243;
yy382:
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy383;
	if(yych != 'u') goto yy243;
yy383:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy384;
	if(yych != 't') goto yy243;
yy384:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy385;
	if(yych != 'e') goto yy243;
yy385:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy386;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy386;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy386;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy386:
	{goto scan_start;}
yy387:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy388;
	if(yych != 't') goto yy243;
yy388:
	yych = *++YYCURSOR;
	if(yych != '-') goto yy243;
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy390;
	if(yych != 'd') goto yy243;
yy390:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy391;
	if(yych != 'e') goto yy243;
yy391:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy392;
	if(yych != 'l') goto yy243;
yy392:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy393;
	if(yych != 'i') goto yy243;
yy393:
	yych = *++YYCURSOR;
	if(yych == 'M') goto yy394;
	if(yych != 'm') goto yy243;
yy394:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy395;
	if(yych != 'i') goto yy243;
yy395:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy396;
	if(yych != 't') goto yy243;
yy396:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy397;
	if(yych != 'e') goto yy243;
yy397:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy398;
	if(yych != 'r') goto yy243;
yy398:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy399;
	if(yych != 's') goto yy243;
yy399:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy400;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy400;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy400;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy400:
	{YYCURSOR = parseDelimiters(YYCURSOR, S_SOFTDELIMITSET); marker = YYCURSOR; goto scan_start;}
yy401:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'R') {
		if(yych <= '"') {
			if(yych <= 0x0000000D) {
				if(yych <= 0x00000008) goto yy243;
			} else {
				if(yych <= 0x0000001B) goto yy243;
				if(yych >= '!') goto yy243;
			}
		} else {
			if(yych <= ')') {
				if(yych <= '#') goto yy402;
				if(yych <= '\'') goto yy243;
			} else {
				if(yych != ';') goto yy243;
			}
		}
	} else {
		if(yych <= 'u') {
			if(yych <= 'V') {
				if(yych <= 'S') goto yy414;
				if(yych <= 'U') goto yy243;
				goto yy416;
			} else {
				if(yych == 's') goto yy414;
				goto yy243;
			}
		} else {
			if(yych <= 0x00000085) {
				if(yych <= 'v') goto yy416;
				if(yych <= 0x00000084) goto yy243;
			} else {
				if(yych <= 0x00002027) goto yy243;
				if(yych >= 0x0000202A) goto yy243;
			}
		}
	}
yy402:
	{YYCURSOR = parseSet(YYCURSOR); marker = YYCURSOR; goto scan_start;}
yy403:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy409;
	if(yych == 't') goto yy409;
	goto yy243;
yy404:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy405;
	if(yych != 'e') goto yy243;
yy405:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy406;
	if(yych != 'c') goto yy243;
yy406:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy407;
	if(yych != 't') goto yy243;
yy407:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy408;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy408;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy408;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy408:
	{goto scan_start;}
yy409:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy410;
	if(yych != 'i') goto yy243;
yy410:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy411;
	if(yych != 'o') goto yy243;
yy411:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy412;
	if(yych != 'n') goto yy243;
yy412:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy413;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy413;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy413;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy413:
	{in_section = true; in_before_sections = in_after_sections = false; goto scan_start;}
yy414:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy415;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy415;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy415;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy415:
	{goto scan_start;}
yy416:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy417;
	if(yych != 'a') goto yy243;
yy417:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy418;
	if(yych != 'r') goto yy243;
yy418:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy419;
	if(yych != 'i') goto yy243;
yy419:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy420;
	if(yych != 'a') goto yy243;
yy420:
	yych = *++YYCURSOR;
	if(yych == 'B') goto yy421;
	if(yych != 'b') goto yy243;
yy421:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy422;
	if(yych != 'l') goto yy243;
yy422:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy423;
	if(yych != 'e') goto yy243;
yy423:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy424;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy424;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy424;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy424:
	{goto scan_start;}
yy425:
	yych = *++YYCURSOR;
	if(yych == 'F') goto yy426;
	if(yych != 'f') goto yy243;
yy426:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy427;
	if(yych != 'o') goto yy243;
yy427:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy428;
	if(yych != 'r') goto yy243;
yy428:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy429;
	if(yych != 'e') goto yy243;
yy429:
	yych = *++YYCURSOR;
	if(yych != '-') goto yy243;
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy431;
	if(yych != 's') goto yy243;
yy431:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy432;
	if(yych != 'e') goto yy243;
yy432:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy433;
	if(yych != 'c') goto yy243;
yy433:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy434;
	if(yych != 't') goto yy243;
yy434:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy435;
	if(yych != 'i') goto yy243;
yy435:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy436;
	if(yych != 'o') goto yy243;
yy436:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy437;
	if(yych != 'n') goto yy243;
yy437:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy438;
	if(yych != 's') goto yy243;
yy438:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy439;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy439;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy439;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy439:
	{in_before_sections = true; in_section = in_after_sections = false; goto scan_start;}
yy440:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy441;
	if(yych != 'e') goto yy243;
yy441:
	yych = *++YYCURSOR;
	if(yych == 'F') goto yy442;
	if(yych != 'f') goto yy243;
yy442:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy443;
	if(yych != 'e') goto yy243;
yy443:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy444;
	if(yych != 'r') goto yy243;
yy444:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy445;
	if(yych != 'r') goto yy243;
yy445:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy446;
	if(yych != 'e') goto yy243;
yy446:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy447;
	if(yych != 'd') goto yy243;
yy447:
	yych = *++YYCURSOR;
	if(yych != '-') goto yy243;
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy449;
	if(yych != 't') goto yy243;
yy449:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy450;
	if(yych != 'a') goto yy243;
yy450:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy451;
	if(yych != 'r') goto yy243;
yy451:
	yych = *++YYCURSOR;
	if(yych == 'G') goto yy452;
	if(yych != 'g') goto yy243;
yy452:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy453;
	if(yych != 'e') goto yy243;
yy453:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy454;
	if(yych != 't') goto yy243;
yy454:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy455;
	if(yych != 's') goto yy243;
yy455:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy243;
			if(yych >= 0x0000000E) goto yy243;
		} else {
			if(yych <= ' ') goto yy456;
			if(yych != '#') goto yy243;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy456;
			if(yych != ';') goto yy243;
		} else {
			if(yych <= 0x00000085) goto yy456;
			if(yych <= 0x00002027) goto yy243;
			if(yych >= 0x0000202A) goto yy243;
		}
	}
yy456:
	{YYCURSOR = parsePreferredTargets(YYCURSOR); marker = YYCURSOR; goto scan_start;}
}


scan_end:
	marker = 0;
	return retval;
}

GPRE2C::GPRE2C() {
	filename = 0;
	locale = 0;
	codepage = 0;
	result = 0;
	option_vislcg_compat = false;
	in_before_sections = false;
	in_after_sections = false;
	in_section = false;
}

GPRE2C::~GPRE2C() {
	filename = 0;
	locale = 0;
	codepage = 0;
	result = 0;
}

void GPRE2C::setResult(CG3::Grammar *res) {
	result = res;
}

void GPRE2C::setCompatible(bool f) {
	option_vislcg_compat = f;
}

int GPRE2C::grammar_from_ufile(UFILE *input) {
	u_frewind(input);
	if (u_feof(input)) {
		u_fprintf(ux_stderr, "Error: Input is null - nothing to parse!\n");
		return -1;
	}
	if (!result) {
		u_fprintf(ux_stderr, "Error: No preallocated grammar provided - cannot continue!\n");
		return -1;
	}
	
	free_keywords();
	free_regexps();
	free_strings();

	int error = init_keywords();
	if (error) {
		u_fprintf(ux_stderr, "Error: init_keywords returned %i!\n", error);
		return error;
	}

	error = init_regexps();
	if (error) {
		u_fprintf(ux_stderr, "Error: init_regexps returned %i!\n", error);
		return error;
	}

	error = init_strings();
	if (error) {
		u_fprintf(ux_stderr, "Error: init_strings returned %i!\n", error);
		return error;
	}

	UChar *buffer = new UChar[result->grammar_size+8];
	memset(buffer, 0, sizeof(UChar)*(result->grammar_size+8));
	u_file_read(buffer, result->grammar_size, input);
	
	UChar *offset = buffer;
	if (u_strlen(offset) > 0) {
		result->lines = 1;
		scan(offset);
	} else {
		u_fprintf(ux_stderr, "Error: Grammar file is empty - nothing to parse!\n");
		return -1;
	}
	
	delete buffer;
	free_regexps();
	free_strings();

	return 0;
}

int GPRE2C::parse_grammar_from_file(const char *fname, const char *loc, const char *cpage) {
	filename = fname;
	locale = loc;
	codepage = cpage;

	if (!result) {
		u_fprintf(ux_stderr, "Error: Cannot parse into nothing - hint: call setResult() before trying.\n");
		return -1;
	}

	struct stat _stat;
	int error = stat(filename, &_stat);

	if (error != 0) {
		u_fprintf(ux_stderr, "Error: Cannot stat %s due to error %d - bailing out!\n", filename, error);
		exit(1);
	} else {
		result->last_modified = (uint32_t)_stat.st_mtime;
		result->grammar_size = (uint32_t)_stat.st_size;
	}

	result->setName(filename);

	UFILE *grammar = u_fopen(filename, "r", locale, codepage);
	if (!grammar) {
		u_fprintf(ux_stderr, "Error: Error opening %s for reading!\n", filename);
		return -1;
	}
	
	error = grammar_from_ufile(grammar);
	if (error) {
		return error;
	}
	return 0;
}
