/* Generated by re2c 0.11.0 on Wed Feb 14 07:47:26 2007 */
/*
 * Copyright (C) 2006, GrammarSoft Aps
 * and the VISL project at the University of Southern Denmark.
 * All Rights Reserved.
 *
 * The contents of this file are subject to the GrammarSoft Public
 * License Version 1.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of
 * the License at http://www.grammarsoft.com/GSPL or
 * http://visl.sdu.dk/GSPL.txt
 * 
 * Software distributed under the License is distributed on an "AS
 * IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * rights and limitations under the License.
 */

#include "stdafx.h"
#include "Strings.h"
#include <unicode/uregex.h>
#include "GrammarParser.h"
#include "Grammar.h"
#include "uextras.h"
#include <sys/stat.h>

using namespace CG3;
using namespace CG3::Strings;
#define YYCURSOR        input



YYCTYPE *GrammarParser::re2c_skipline(YYCTYPE *input) {
skipline_start:

{
	YYCTYPE yych;

	yych = *YYCURSOR;
	if(yych <= 0x0000000C) {
		if(yych <= 0x00000009) {
			if(yych >= 0x00000001) goto yy6;
		} else {
			if(yych == 0x0000000B) goto yy6;
			goto yy4;
		}
	} else {
		if(yych <= 0x00002027) {
			if(yych == 0x00000085) goto yy4;
			goto yy6;
		} else {
			if(yych <= 0x00002029) goto yy4;
			if(yych <= 0x0000FFFF) goto yy6;
		}
	}
	++YYCURSOR;
	{goto skipline_end;}
yy4:
	++YYCURSOR;
	{result->lines++; goto skipline_end;}
yy6:
	++YYCURSOR;
	{goto skipline_start;}
}

skipline_end:
	return YYCURSOR;
}

YYCTYPE *GrammarParser::re2c_parseCompositeTag(YYCTYPE *input, Set *set) {
	CG3::CompositeTag *ctag = result->allocateCompositeTag();
	marker = YYCURSOR;

parseCompositeTag_start:

{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if(yych <= '\'') {
		if(yych <= 0x0000000C) {
			if(yych <= 0x00000009) {
				if(yych <= 0x00000000) goto yy10;
				if(yych <= 0x00000008) goto yy14;
				goto yy25;
			} else {
				if(yych == 0x0000000B) goto yy25;
				goto yy12;
			}
		} else {
			if(yych <= ' ') {
				if(yych <= 0x0000000D) goto yy25;
				if(yych <= 0x0000001B) goto yy14;
				goto yy25;
			} else {
				if(yych == '#') goto yy17;
				goto yy14;
			}
		}
	} else {
		if(yych <= '\\') {
			if(yych <= ':') {
				if(yych <= '(') goto yy19;
				if(yych <= ')') goto yy21;
				goto yy14;
			} else {
				if(yych <= ';') goto yy23;
				if(yych <= '[') goto yy14;
				goto yy16;
			}
		} else {
			if(yych <= 0x00002027) {
				if(yych == 0x00000085) goto yy12;
				goto yy14;
			} else {
				if(yych <= 0x00002029) goto yy12;
				if(yych <= 0x0000FFFF) goto yy14;
			}
		}
	}
yy10:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy28;
			if(yych >= 0x0000000E) goto yy28;
		} else {
			if(yych <= ' ') goto yy11;
			if(yych != '#') goto yy28;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy11;
			if(yych != ';') goto yy28;
		} else {
			if(yych <= 0x00000085) goto yy11;
			if(yych <= 0x00002027) goto yy28;
			if(yych >= 0x0000202A) goto yy28;
		}
	}
yy11:
	{goto parseCompositeTag_end;}
yy12:
	++YYCURSOR;
	{
		marker = YYCURSOR;
		result->lines++;
		goto parseCompositeTag_start;
		}
yy14:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy28;
yy15:
	{
		size_t length = (YYCURSOR - marker)+1;
		YYCTYPE *buffer = new YYCTYPE[length];
		buffer[length-1] = 0;
		u_strncpy(buffer, marker, (int32_t)length-1);
		CG3::Tag *tag = result->allocateTag(buffer);
		result->addTagToCompositeTag(tag, ctag);
		delete buffer;
		marker = YYCURSOR;
		goto parseCompositeTag_start;
		}
yy16:
	yych = *++YYCURSOR;
	if(yych <= '\'') {
		if(yych == '#') goto yy27;
		goto yy28;
	} else {
		if(yych <= ')') goto yy27;
		if(yych == ';') goto yy27;
		goto yy28;
	}
yy17:
	++YYCURSOR;
	{
		YYCURSOR = re2c_skipline(YYCURSOR);
		marker = YYCURSOR;
		goto parseCompositeTag_start;
		}
yy19:
	++YYCURSOR;
	{u_fprintf(ux_stderr, "Error: Mismatched ( on line %u!\n", result->lines); exit(1);}
yy21:
	++YYCURSOR;
	{goto parseCompositeTag_end;}
yy23:
	++YYCURSOR;
	{u_fprintf(ux_stderr, "Error: Found ; before ) on line %u!\n", result->lines); exit(1);}
yy25:
	++YYCURSOR;
	{
		marker = YYCURSOR;
		goto parseCompositeTag_start;
		}
yy27:
	++YYCURSOR;
	yych = *YYCURSOR;
yy28:
	if(yych <= ')') {
		if(yych <= ' ') {
			if(yych <= 0x00000008) goto yy27;
			if(yych <= 0x0000000D) goto yy15;
			if(yych <= 0x0000001B) goto yy27;
			goto yy15;
		} else {
			if(yych == '#') goto yy15;
			if(yych <= '\'') goto yy27;
			goto yy15;
		}
	} else {
		if(yych <= '\\') {
			if(yych == ';') goto yy15;
			if(yych <= '[') goto yy27;
		} else {
			if(yych <= 0x00000085) {
				if(yych <= 0x00000084) goto yy27;
				goto yy15;
			} else {
				if(yych <= 0x00002027) goto yy27;
				if(yych <= 0x00002029) goto yy15;
				goto yy27;
			}
		}
	}
yy29:
	++YYCURSOR;
	yych = *YYCURSOR;
	if(yych <= '[') {
		if(yych <= 0x0000000D) {
			if(yych <= 0x00000008) goto yy27;
			goto yy15;
		} else {
			if(yych <= 0x0000001B) goto yy27;
			if(yych <= ' ') goto yy15;
			goto yy27;
		}
	} else {
		if(yych <= 0x00000085) {
			if(yych <= '\\') goto yy29;
			if(yych <= 0x00000084) goto yy27;
			goto yy15;
		} else {
			if(yych <= 0x00002027) goto yy27;
			if(yych <= 0x00002029) goto yy15;
			goto yy27;
		}
	}
}


parseCompositeTag_end:
	if (ctag->tags_map.empty()) {
		u_fprintf(ux_stderr, "Error: Empty () on line %u!\n", result->lines);
		exit(1);
	}
	result->addCompositeTagToSet(set, ctag);
	return YYCURSOR;
}

YYCTYPE *GrammarParser::re2c_parseInlineSet(YYCTYPE *input, Set **ret_set) {
	CG3::Set *curset = result->allocateSet();
	curset->line = result->lines;
	curset->setName((uint32_t)0);
	CG3::CompositeTag *ctag = result->allocateCompositeTag();
	marker = YYCURSOR;

parseInlineSet_start:

{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if(yych <= '\'') {
		if(yych <= 0x0000000C) {
			if(yych <= 0x00000009) {
				if(yych <= 0x00000000) goto yy33;
				if(yych <= 0x00000008) goto yy37;
				goto yy48;
			} else {
				if(yych == 0x0000000B) goto yy48;
				goto yy35;
			}
		} else {
			if(yych <= ' ') {
				if(yych <= 0x0000000D) goto yy48;
				if(yych <= 0x0000001B) goto yy37;
				goto yy48;
			} else {
				if(yych == '#') goto yy40;
				goto yy37;
			}
		}
	} else {
		if(yych <= '\\') {
			if(yych <= ':') {
				if(yych <= '(') goto yy42;
				if(yych <= ')') goto yy44;
				goto yy37;
			} else {
				if(yych <= ';') goto yy46;
				if(yych <= '[') goto yy37;
				goto yy39;
			}
		} else {
			if(yych <= 0x00002027) {
				if(yych == 0x00000085) goto yy35;
				goto yy37;
			} else {
				if(yych <= 0x00002029) goto yy35;
				if(yych <= 0x0000FFFF) goto yy37;
			}
		}
	}
yy33:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy51;
			if(yych >= 0x0000000E) goto yy51;
		} else {
			if(yych <= ' ') goto yy34;
			if(yych != '#') goto yy51;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy34;
			if(yych != ';') goto yy51;
		} else {
			if(yych <= 0x00000085) goto yy34;
			if(yych <= 0x00002027) goto yy51;
			if(yych >= 0x0000202A) goto yy51;
		}
	}
yy34:
	{goto parseInlineSet_end;}
yy35:
	++YYCURSOR;
	{marker = YYCURSOR; result->lines++; goto parseInlineSet_start;}
yy37:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy51;
yy38:
	{
		size_t length = (YYCURSOR - marker)+1;
		YYCTYPE *buffer = new YYCTYPE[length];
		buffer[length-1] = 0;
		u_strncpy(buffer, marker, (int32_t)length-1);
		CG3::Tag *tag = result->allocateTag(buffer);
		result->addTagToCompositeTag(tag, ctag);
		delete buffer;
		marker = YYCURSOR;
		goto parseInlineSet_start;
		}
yy39:
	yych = *++YYCURSOR;
	if(yych <= '\'') {
		if(yych == '#') goto yy50;
		goto yy51;
	} else {
		if(yych <= ')') goto yy50;
		if(yych == ';') goto yy50;
		goto yy51;
	}
yy40:
	++YYCURSOR;
	{YYCURSOR = re2c_skipline(YYCURSOR);marker = YYCURSOR;goto parseInlineSet_start;}
yy42:
	++YYCURSOR;
	{u_fprintf(ux_stderr, "Error: Mismatched ( on line %u!\n", result->lines); exit(1);}
yy44:
	++YYCURSOR;
	{goto parseInlineSet_end;}
yy46:
	++YYCURSOR;
	{u_fprintf(ux_stderr, "Error: Found ; before ) on line %u!\n", result->lines); exit(1);}
yy48:
	++YYCURSOR;
	{
		marker = YYCURSOR;
		goto parseInlineSet_start;
		}
yy50:
	++YYCURSOR;
	yych = *YYCURSOR;
yy51:
	if(yych <= ')') {
		if(yych <= ' ') {
			if(yych <= 0x00000008) goto yy50;
			if(yych <= 0x0000000D) goto yy38;
			if(yych <= 0x0000001B) goto yy50;
			goto yy38;
		} else {
			if(yych == '#') goto yy38;
			if(yych <= '\'') goto yy50;
			goto yy38;
		}
	} else {
		if(yych <= '\\') {
			if(yych == ';') goto yy38;
			if(yych <= '[') goto yy50;
		} else {
			if(yych <= 0x00000085) {
				if(yych <= 0x00000084) goto yy50;
				goto yy38;
			} else {
				if(yych <= 0x00002027) goto yy50;
				if(yych <= 0x00002029) goto yy38;
				goto yy50;
			}
		}
	}
yy52:
	++YYCURSOR;
	yych = *YYCURSOR;
	if(yych <= '[') {
		if(yych <= 0x0000000D) {
			if(yych <= 0x00000008) goto yy50;
			goto yy38;
		} else {
			if(yych <= 0x0000001B) goto yy50;
			if(yych <= ' ') goto yy38;
			goto yy50;
		}
	} else {
		if(yych <= 0x00000085) {
			if(yych <= '\\') goto yy52;
			if(yych <= 0x00000084) goto yy50;
			goto yy38;
		} else {
			if(yych <= 0x00002027) goto yy50;
			if(yych <= 0x00002029) goto yy38;
			goto yy50;
		}
	}
}


parseInlineSet_end:
	result->addCompositeTagToSet(curset, ctag);
	result->addSet(curset);
	*ret_set = curset;
	return YYCURSOR;
}

YYCTYPE *GrammarParser::re2c_parseSetList(YYCTYPE *input, Set *set) {
	bool want_set = true;
	marker = YYCURSOR;
	if (result->lines == 1333) {
		input=input;
	}

parseSetList_start:

{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if(yych <= '-') {
		if(yych <= ' ') {
			if(yych <= 0x0000000A) {
				if(yych <= 0x00000000) goto yy56;
				if(yych <= 0x00000008) goto yy64;
				if(yych <= 0x00000009) goto yy71;
				goto yy58;
			} else {
				if(yych <= 0x0000000C) {
					if(yych <= 0x0000000B) goto yy71;
					goto yy58;
				} else {
					if(yych <= 0x0000000D) goto yy71;
					if(yych <= 0x0000001B) goto yy64;
					goto yy71;
				}
			}
		} else {
			if(yych <= '\'') {
				if(yych <= '!') goto yy60;
				if(yych == '#') goto yy65;
				goto yy64;
			} else {
				if(yych <= ')') {
					if(yych <= '(') goto yy67;
					goto yy69;
				} else {
					if(yych == ',') goto yy64;
					goto yy60;
				}
			}
		}
	} else {
		if(yych <= 'n') {
			if(yych <= 'O') {
				if(yych == ';') goto yy73;
				if(yych <= 'N') goto yy64;
				goto yy62;
			} else {
				if(yych <= '\\') {
					if(yych <= '[') goto yy64;
					goto yy66;
				} else {
					if(yych == '^') goto yy60;
					goto yy64;
				}
			}
		} else {
			if(yych <= 0x00000084) {
				if(yych <= 'o') goto yy62;
				if(yych == '|') goto yy60;
				goto yy64;
			} else {
				if(yych <= 0x00002027) {
					if(yych <= 0x00000085) goto yy58;
					goto yy64;
				} else {
					if(yych <= 0x00002029) goto yy58;
					if(yych <= 0x0000FFFF) goto yy64;
				}
			}
		}
	}
yy56:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ')') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy76;
			if(yych >= 0x0000000E) goto yy76;
		} else {
			if(yych <= ' ') goto yy57;
			if(yych <= '\'') goto yy76;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych != ';') goto yy76;
		} else {
			if(yych <= 0x00000085) goto yy57;
			if(yych <= 0x00002027) goto yy76;
			if(yych >= 0x0000202A) goto yy76;
		}
	}
yy57:
	{goto parseSetList_end;}
yy58:
	++YYCURSOR;
	{marker = YYCURSOR; result->lines++; goto parseSetList_start;}
yy60:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ')') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy76;
			if(yych >= 0x0000000E) goto yy76;
		} else {
			if(yych <= ' ') goto yy61;
			if(yych <= '\'') goto yy76;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych != ';') goto yy76;
		} else {
			if(yych <= 0x00000085) goto yy61;
			if(yych <= 0x00002027) goto yy76;
			if(yych >= 0x0000202A) goto yy76;
		}
	}
yy61:
	{
		size_t length = (YYCURSOR - marker)+1;
		YYCTYPE *buffer = new YYCTYPE[length];
		buffer[length-1] = 0;
		u_strncpy(buffer, marker, (int32_t)length-1);
		if (want_set) {
			u_fprintf(ux_stderr, "Error: Missing set for operator %S on line %u!\n", buffer, result->lines);
			exit(1);
		}
		uint32_t set_op = ux_isSetOp(buffer);
		set->set_ops.push_back(set_op);
		want_set = true;
		marker = YYCURSOR;
		goto parseSetList_start;
		}
yy62:
	++YYCURSOR;
	if((yych = *YYCURSOR) == 'R') goto yy79;
	if(yych == 'r') goto yy79;
	goto yy76;
yy63:
	{
		if (!want_set) {
			return YYCURSOR;
		}
		size_t length = (YYCURSOR - marker)+1;
		YYCTYPE *buffer = new YYCTYPE[length];
		buffer[length-1] = 0;
		u_strncpy(buffer, marker, (int32_t)length-1);
		uint32_t set_hash = hash_sdbm_uchar(buffer, 0);
		if (result->set_alias.find(set_hash) != result->set_alias.end()) {
			set_hash = result->set_alias[set_hash];
		}
		set_hash = result->getSet(set_hash)->hash;
		set->sets.push_back(set_hash);
		delete buffer;
		marker = YYCURSOR;
		want_set = false;
		goto parseSetList_start;
		}
yy64:
	yych = *++YYCURSOR;
	goto yy76;
yy65:
	yych = *++YYCURSOR;
	goto yy76;
yy66:
	yych = *++YYCURSOR;
	if(yych <= '\'') goto yy76;
	if(yych <= ')') goto yy75;
	if(yych == ';') goto yy75;
	goto yy76;
yy67:
	++YYCURSOR;
	{
		if (!want_set) {
			return YYCURSOR;
		}
		Set *ret_set = 0;
		YYCURSOR = re2c_parseInlineSet(YYCURSOR, &ret_set);
		uint32_t set_hash = ret_set->hash;
		if (result->set_alias.find(set_hash) != result->set_alias.end()) {
			set_hash = result->set_alias[set_hash];
		}
		set->sets.push_back(set_hash);
		marker = YYCURSOR;
		want_set = false;
		goto parseSetList_start;
		}
yy69:
	++YYCURSOR;
	{u_fprintf(ux_stderr, "Error: Mismatched ) on line %u!\n", result->lines); exit(1);}
yy71:
	++YYCURSOR;
	{marker = YYCURSOR; goto parseSetList_start;}
yy73:
	++YYCURSOR;
	{goto parseSetList_end;}
yy75:
	++YYCURSOR;
	yych = *YYCURSOR;
yy76:
	if(yych <= ':') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy75;
			if(yych <= 0x0000000D) goto yy63;
			goto yy75;
		} else {
			if(yych <= ' ') goto yy63;
			if(yych <= '\'') goto yy75;
			if(yych <= ')') goto yy63;
			goto yy75;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ';') goto yy63;
			if(yych != '\\') goto yy75;
		} else {
			if(yych <= 0x00000085) goto yy63;
			if(yych <= 0x00002027) goto yy75;
			if(yych <= 0x00002029) goto yy63;
			goto yy75;
		}
	}
yy77:
	++YYCURSOR;
	yych = *YYCURSOR;
	if(yych <= '[') {
		if(yych <= 0x0000000D) {
			if(yych <= 0x00000008) goto yy75;
			goto yy63;
		} else {
			if(yych <= 0x0000001B) goto yy75;
			if(yych <= ' ') goto yy63;
			goto yy75;
		}
	} else {
		if(yych <= 0x00000085) {
			if(yych <= '\\') goto yy77;
			if(yych <= 0x00000084) goto yy75;
			goto yy63;
		} else {
			if(yych <= 0x00002027) goto yy75;
			if(yych <= 0x00002029) goto yy63;
			goto yy75;
		}
	}
yy79:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ')') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy76;
			if(yych <= 0x0000000D) goto yy61;
			goto yy76;
		} else {
			if(yych <= ' ') goto yy61;
			if(yych <= '\'') goto yy76;
			goto yy61;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych == ';') goto yy61;
			goto yy76;
		} else {
			if(yych <= 0x00000085) goto yy61;
			if(yych <= 0x00002027) goto yy76;
			if(yych <= 0x00002029) goto yy61;
			goto yy76;
		}
	}
}


parseSetList_end:
	return YYCURSOR;
}

YYCTYPE *GrammarParser::re2c_parseTagList(YYCTYPE *input, Set *set) {
	marker = YYCURSOR;

parseTagList_start:

{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if(yych <= '\'') {
		if(yych <= 0x0000000C) {
			if(yych <= 0x00000009) {
				if(yych <= 0x00000000) goto yy82;
				if(yych <= 0x00000008) goto yy86;
				goto yy97;
			} else {
				if(yych == 0x0000000B) goto yy97;
				goto yy84;
			}
		} else {
			if(yych <= ' ') {
				if(yych <= 0x0000000D) goto yy97;
				if(yych <= 0x0000001B) goto yy86;
				goto yy97;
			} else {
				if(yych == '#') goto yy93;
				goto yy86;
			}
		}
	} else {
		if(yych <= '\\') {
			if(yych <= ':') {
				if(yych <= '(') goto yy89;
				if(yych <= ')') goto yy91;
				goto yy86;
			} else {
				if(yych <= ';') goto yy95;
				if(yych <= '[') goto yy86;
				goto yy88;
			}
		} else {
			if(yych <= 0x00002027) {
				if(yych == 0x00000085) goto yy84;
				goto yy86;
			} else {
				if(yych <= 0x00002029) goto yy84;
				if(yych <= 0x0000FFFF) goto yy86;
			}
		}
	}
yy82:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy100;
			if(yych >= 0x0000000E) goto yy100;
		} else {
			if(yych <= ' ') goto yy83;
			if(yych != '#') goto yy100;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy83;
			if(yych != ';') goto yy100;
		} else {
			if(yych <= 0x00000085) goto yy83;
			if(yych <= 0x00002027) goto yy100;
			if(yych >= 0x0000202A) goto yy100;
		}
	}
yy83:
	{goto parseTagList_end;}
yy84:
	++YYCURSOR;
	{
		marker = YYCURSOR;
		result->lines++;
		goto parseTagList_start;
		}
yy86:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy100;
yy87:
	{
		size_t length = (YYCURSOR - marker)+1;
		YYCTYPE *buffer = new YYCTYPE[length];
		buffer[length-1] = 0;
		u_strncpy(buffer, marker, (int32_t)length-1);
		CG3::CompositeTag *ctag = result->allocateCompositeTag();
		CG3::Tag *tag = result->allocateTag(buffer);
		result->addTagToCompositeTag(tag, ctag);
		result->addCompositeTagToSet(set, ctag);
		delete buffer;
		marker = YYCURSOR;
		goto parseTagList_start;
		}
yy88:
	yych = *++YYCURSOR;
	if(yych <= '\'') {
		if(yych == '#') goto yy99;
		goto yy100;
	} else {
		if(yych <= ')') goto yy99;
		if(yych == ';') goto yy99;
		goto yy100;
	}
yy89:
	++YYCURSOR;
	{
		YYCURSOR = re2c_parseCompositeTag(YYCURSOR, set);
		marker = YYCURSOR;
		goto parseTagList_start;
		}
yy91:
	++YYCURSOR;
	{u_fprintf(ux_stderr, "Error: Mismatched ) on line %u!\n", result->lines); exit(1);}
yy93:
	++YYCURSOR;
	{
		YYCURSOR = re2c_skipline(YYCURSOR);
		marker = YYCURSOR;
		goto parseTagList_start;
		}
yy95:
	++YYCURSOR;
	{goto parseTagList_end;}
yy97:
	++YYCURSOR;
	{
		marker = YYCURSOR;
		goto parseTagList_start;
		}
yy99:
	++YYCURSOR;
	yych = *YYCURSOR;
yy100:
	if(yych <= ')') {
		if(yych <= ' ') {
			if(yych <= 0x00000008) goto yy99;
			if(yych <= 0x0000000D) goto yy87;
			if(yych <= 0x0000001B) goto yy99;
			goto yy87;
		} else {
			if(yych == '#') goto yy87;
			if(yych <= '\'') goto yy99;
			goto yy87;
		}
	} else {
		if(yych <= '\\') {
			if(yych == ';') goto yy87;
			if(yych <= '[') goto yy99;
		} else {
			if(yych <= 0x00000085) {
				if(yych <= 0x00000084) goto yy99;
				goto yy87;
			} else {
				if(yych <= 0x00002027) goto yy99;
				if(yych <= 0x00002029) goto yy87;
				goto yy99;
			}
		}
	}
yy101:
	++YYCURSOR;
	yych = *YYCURSOR;
	if(yych <= '[') {
		if(yych <= 0x0000000D) {
			if(yych <= 0x00000008) goto yy99;
			goto yy87;
		} else {
			if(yych <= 0x0000001B) goto yy99;
			if(yych <= ' ') goto yy87;
			goto yy99;
		}
	} else {
		if(yych <= 0x00000085) {
			if(yych <= '\\') goto yy101;
			if(yych <= 0x00000084) goto yy99;
			goto yy87;
		} else {
			if(yych <= 0x00002027) goto yy99;
			if(yych <= 0x00002029) goto yy87;
			goto yy99;
		}
	}
}


parseTagList_end:
	return YYCURSOR;
}

YYCTYPE *GrammarParser::re2c_parseDelimiters(YYCTYPE *input) {
	CG3::Set *curset = result->allocateSet();
	curset->setName(stringbits[S_DELIMITSET]);
	curset->line = result->lines;

parseDelimiters_start:

{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if(yych <= ':') {
		if(yych <= 0x0000000B) {
			if(yych <= 0x00000000) goto yy105;
			if(yych == 0x0000000A) goto yy107;
			goto yy115;
		} else {
			if(yych <= 0x0000000C) goto yy107;
			if(yych == '#') goto yy111;
			goto yy115;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ';') goto yy113;
			if(yych == '=') goto yy109;
			goto yy115;
		} else {
			if(yych <= 0x00002027) {
				if(yych <= 0x00000085) goto yy107;
				goto yy115;
			} else {
				if(yych <= 0x00002029) goto yy107;
				if(yych <= 0x0000FFFF) goto yy115;
			}
		}
	}
yy105:
	++YYCURSOR;
	{goto parseDelimiters_end;}
yy107:
	++YYCURSOR;
	{result->lines++; goto parseDelimiters_start;}
yy109:
	++YYCURSOR;
	{YYCURSOR = re2c_parseTagList(YYCURSOR, curset); goto parseDelimiters_end;}
yy111:
	++YYCURSOR;
	{YYCURSOR = re2c_skipline(YYCURSOR); goto parseDelimiters_start;}
yy113:
	++YYCURSOR;
	{goto parseDelimiters_end;}
yy115:
	++YYCURSOR;
	{goto parseDelimiters_start;}
}


parseDelimiters_end:
	result->addSet(curset);
	result->delimiters = curset;
	return YYCURSOR;
}

YYCTYPE *GrammarParser::re2c_parseList(YYCTYPE *input) {
	marker = YYCURSOR;
	CG3::Set *curset = result->allocateSet();
	curset->line = result->lines;

parseList_start:

{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if(yych <= '\'') {
		if(yych <= 0x0000000C) {
			if(yych <= 0x00000009) {
				if(yych <= 0x00000000) goto yy119;
				if(yych <= 0x00000008) goto yy127;
				goto yy132;
			} else {
				if(yych == 0x0000000B) goto yy132;
				goto yy121;
			}
		} else {
			if(yych <= ' ') {
				if(yych <= 0x0000000D) goto yy132;
				if(yych <= 0x0000001B) goto yy127;
				goto yy132;
			} else {
				if(yych == '#') goto yy125;
				goto yy127;
			}
		}
	} else {
		if(yych <= '[') {
			if(yych <= ';') {
				if(yych <= ')') goto yy132;
				if(yych <= ':') goto yy127;
				goto yy130;
			} else {
				if(yych == '=') goto yy123;
				goto yy127;
			}
		} else {
			if(yych <= 0x00000085) {
				if(yych <= '\\') goto yy129;
				if(yych <= 0x00000084) goto yy127;
				goto yy121;
			} else {
				if(yych <= 0x00002027) goto yy127;
				if(yych <= 0x00002029) goto yy121;
				if(yych <= 0x0000FFFF) goto yy127;
			}
		}
	}
yy119:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ')') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy135;
			if(yych >= 0x0000000E) goto yy135;
		} else {
			if(yych <= ' ') goto yy120;
			if(yych <= '\'') goto yy135;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych != ';') goto yy135;
		} else {
			if(yych <= 0x00000085) goto yy120;
			if(yych <= 0x00002027) goto yy135;
			if(yych >= 0x0000202A) goto yy135;
		}
	}
yy120:
	{goto parseList_end;}
yy121:
	++YYCURSOR;
	{marker = YYCURSOR; result->lines++; goto parseList_start;}
yy123:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ')') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy135;
			if(yych >= 0x0000000E) goto yy135;
		} else {
			if(yych <= ' ') goto yy124;
			if(yych <= '\'') goto yy135;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych != ';') goto yy135;
		} else {
			if(yych <= 0x00000085) goto yy124;
			if(yych <= 0x00002027) goto yy135;
			if(yych >= 0x0000202A) goto yy135;
		}
	}
yy124:
	{YYCURSOR = re2c_parseTagList(YYCURSOR, curset); marker = YYCURSOR; goto parseList_end;}
yy125:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ')') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy135;
			if(yych >= 0x0000000E) goto yy135;
		} else {
			if(yych <= ' ') goto yy126;
			if(yych <= '\'') goto yy135;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych != ';') goto yy135;
		} else {
			if(yych <= 0x00000085) goto yy126;
			if(yych <= 0x00002027) goto yy135;
			if(yych >= 0x0000202A) goto yy135;
		}
	}
yy126:
	{YYCURSOR = re2c_skipline(YYCURSOR); marker = YYCURSOR; goto parseList_start;}
yy127:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy135;
yy128:
	{
		size_t length = (YYCURSOR - marker)+1;
		YYCTYPE *buffer = new YYCTYPE[length];
		buffer[length-1] = 0;
		u_strncpy(buffer, marker, (int32_t)length-1);
		curset->setName(buffer);
		delete buffer;
		marker = YYCURSOR;
		goto parseList_start;
		}
yy129:
	yych = *++YYCURSOR;
	if(yych <= '\'') goto yy135;
	if(yych <= ')') goto yy134;
	if(yych == ';') goto yy134;
	goto yy135;
yy130:
	++YYCURSOR;
	{goto parseList_end;}
yy132:
	++YYCURSOR;
	{marker = YYCURSOR; goto parseList_start;}
yy134:
	++YYCURSOR;
	yych = *YYCURSOR;
yy135:
	if(yych <= ':') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy134;
			if(yych <= 0x0000000D) goto yy128;
			goto yy134;
		} else {
			if(yych <= ' ') goto yy128;
			if(yych <= '\'') goto yy134;
			if(yych <= ')') goto yy128;
			goto yy134;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ';') goto yy128;
			if(yych != '\\') goto yy134;
		} else {
			if(yych <= 0x00000085) goto yy128;
			if(yych <= 0x00002027) goto yy134;
			if(yych <= 0x00002029) goto yy128;
			goto yy134;
		}
	}
yy136:
	++YYCURSOR;
	yych = *YYCURSOR;
	if(yych <= '[') {
		if(yych <= 0x0000000D) {
			if(yych <= 0x00000008) goto yy134;
			goto yy128;
		} else {
			if(yych <= 0x0000001B) goto yy134;
			if(yych <= ' ') goto yy128;
			goto yy134;
		}
	} else {
		if(yych <= 0x00000085) {
			if(yych <= '\\') goto yy136;
			if(yych <= 0x00000084) goto yy134;
			goto yy128;
		} else {
			if(yych <= 0x00002027) goto yy134;
			if(yych <= 0x00002029) goto yy128;
			goto yy134;
		}
	}
}


parseList_end:
	result->addSet(curset);
	return YYCURSOR;
}

YYCTYPE *GrammarParser::re2c_parseSet(YYCTYPE *input) {
	marker = YYCURSOR;
	CG3::Set *curset = result->allocateSet();
	curset->line = result->lines;
	if (result->lines == 1333) {
		input=input;
	}

parseSet_start:

{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if(yych <= '\'') {
		if(yych <= 0x0000000C) {
			if(yych <= 0x00000009) {
				if(yych <= 0x00000000) goto yy140;
				if(yych <= 0x00000008) goto yy148;
				goto yy153;
			} else {
				if(yych == 0x0000000B) goto yy153;
				goto yy142;
			}
		} else {
			if(yych <= ' ') {
				if(yych <= 0x0000000D) goto yy153;
				if(yych <= 0x0000001B) goto yy148;
				goto yy153;
			} else {
				if(yych == '#') goto yy146;
				goto yy148;
			}
		}
	} else {
		if(yych <= '[') {
			if(yych <= ';') {
				if(yych <= ')') goto yy153;
				if(yych <= ':') goto yy148;
				goto yy151;
			} else {
				if(yych == '=') goto yy144;
				goto yy148;
			}
		} else {
			if(yych <= 0x00000085) {
				if(yych <= '\\') goto yy150;
				if(yych <= 0x00000084) goto yy148;
				goto yy142;
			} else {
				if(yych <= 0x00002027) goto yy148;
				if(yych <= 0x00002029) goto yy142;
				if(yych <= 0x0000FFFF) goto yy148;
			}
		}
	}
yy140:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ')') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy156;
			if(yych >= 0x0000000E) goto yy156;
		} else {
			if(yych <= ' ') goto yy141;
			if(yych <= '\'') goto yy156;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych != ';') goto yy156;
		} else {
			if(yych <= 0x00000085) goto yy141;
			if(yych <= 0x00002027) goto yy156;
			if(yych >= 0x0000202A) goto yy156;
		}
	}
yy141:
	{goto parseSet_end;}
yy142:
	++YYCURSOR;
	{marker = YYCURSOR; result->lines++; goto parseSet_start;}
yy144:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ')') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy156;
			if(yych >= 0x0000000E) goto yy156;
		} else {
			if(yych <= ' ') goto yy145;
			if(yych <= '\'') goto yy156;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych != ';') goto yy156;
		} else {
			if(yych <= 0x00000085) goto yy145;
			if(yych <= 0x00002027) goto yy156;
			if(yych >= 0x0000202A) goto yy156;
		}
	}
yy145:
	{YYCURSOR = re2c_parseSetList(YYCURSOR, curset); marker = YYCURSOR; goto parseSet_end;}
yy146:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ')') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy156;
			if(yych >= 0x0000000E) goto yy156;
		} else {
			if(yych <= ' ') goto yy147;
			if(yych <= '\'') goto yy156;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych != ';') goto yy156;
		} else {
			if(yych <= 0x00000085) goto yy147;
			if(yych <= 0x00002027) goto yy156;
			if(yych >= 0x0000202A) goto yy156;
		}
	}
yy147:
	{YYCURSOR = re2c_skipline(YYCURSOR); marker = YYCURSOR; goto parseSet_start;}
yy148:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy156;
yy149:
	{
		size_t length = (YYCURSOR - marker)+1;
		YYCTYPE *buffer = new YYCTYPE[length];
		buffer[length-1] = 0;
		u_strncpy(buffer, marker, (int32_t)length-1);
		curset->setName(buffer);
		delete buffer;
		marker = YYCURSOR;
		goto parseSet_start;
		}
yy150:
	yych = *++YYCURSOR;
	if(yych <= '\'') goto yy156;
	if(yych <= ')') goto yy155;
	if(yych == ';') goto yy155;
	goto yy156;
yy151:
	++YYCURSOR;
	{goto parseSet_end;}
yy153:
	++YYCURSOR;
	{marker = YYCURSOR; goto parseSet_start;}
yy155:
	++YYCURSOR;
	yych = *YYCURSOR;
yy156:
	if(yych <= ':') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy155;
			if(yych <= 0x0000000D) goto yy149;
			goto yy155;
		} else {
			if(yych <= ' ') goto yy149;
			if(yych <= '\'') goto yy155;
			if(yych <= ')') goto yy149;
			goto yy155;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ';') goto yy149;
			if(yych != '\\') goto yy155;
		} else {
			if(yych <= 0x00000085) goto yy149;
			if(yych <= 0x00002027) goto yy155;
			if(yych <= 0x00002029) goto yy149;
			goto yy155;
		}
	}
yy157:
	++YYCURSOR;
	yych = *YYCURSOR;
	if(yych <= '[') {
		if(yych <= 0x0000000D) {
			if(yych <= 0x00000008) goto yy155;
			goto yy149;
		} else {
			if(yych <= 0x0000001B) goto yy155;
			if(yych <= ' ') goto yy149;
			goto yy155;
		}
	} else {
		if(yych <= 0x00000085) {
			if(yych <= '\\') goto yy157;
			if(yych <= 0x00000084) goto yy155;
			goto yy149;
		} else {
			if(yych <= 0x00002027) goto yy155;
			if(yych <= 0x00002029) goto yy149;
			goto yy155;
		}
	}
}


parseSet_end:
	if (curset->sets.size() == 1) {
		uint32_t res = curset->sets.at(0);
		result->set_alias[hash_sdbm_uchar(curset->name, 0)] = res;
		result->destroySet(curset);
		curset = result->getSet(res);
	}
	result->addSet(curset);
	return YYCURSOR;
}

YYCTYPE *GrammarParser::re2c_parsePreferredTargets(YYCTYPE *input) {
	marker = YYCURSOR;

parsePreferredTargets_start:

{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if(yych <= '\'') {
		if(yych <= 0x0000000C) {
			if(yych <= 0x00000009) {
				if(yych <= 0x00000000) goto yy161;
				if(yych <= 0x00000008) goto yy165;
				goto yy176;
			} else {
				if(yych == 0x0000000B) goto yy176;
				goto yy163;
			}
		} else {
			if(yych <= ' ') {
				if(yych <= 0x0000000D) goto yy176;
				if(yych <= 0x0000001B) goto yy165;
				goto yy176;
			} else {
				if(yych == '#') goto yy172;
				goto yy165;
			}
		}
	} else {
		if(yych <= '\\') {
			if(yych <= ':') {
				if(yych <= '(') goto yy168;
				if(yych <= ')') goto yy170;
				goto yy165;
			} else {
				if(yych <= ';') goto yy174;
				if(yych <= '[') goto yy165;
				goto yy167;
			}
		} else {
			if(yych <= 0x00002027) {
				if(yych == 0x00000085) goto yy163;
				goto yy165;
			} else {
				if(yych <= 0x00002029) goto yy163;
				if(yych <= 0x0000FFFF) goto yy165;
			}
		}
	}
yy161:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy179;
			if(yych >= 0x0000000E) goto yy179;
		} else {
			if(yych <= ' ') goto yy162;
			if(yych != '#') goto yy179;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy162;
			if(yych != ';') goto yy179;
		} else {
			if(yych <= 0x00000085) goto yy162;
			if(yych <= 0x00002027) goto yy179;
			if(yych >= 0x0000202A) goto yy179;
		}
	}
yy162:
	{goto parsePreferredTargets_end;}
yy163:
	++YYCURSOR;
	{
		marker = YYCURSOR;
		result->lines++;
		goto parsePreferredTargets_start;
		}
yy165:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy179;
yy166:
	{
		size_t length = (YYCURSOR - marker)+1;
		YYCTYPE *buffer = new YYCTYPE[length];
		buffer[length-1] = 0;
		u_strncpy(buffer, marker, (int32_t)length-1);
		if (!(buffer[0] == '=' && u_strlen(buffer) == 1)) {
			result->addPreferredTarget(buffer);
		}
		delete buffer;
		marker = YYCURSOR;
		goto parsePreferredTargets_start;
		}
yy167:
	yych = *++YYCURSOR;
	if(yych <= '\'') {
		if(yych == '#') goto yy178;
		goto yy179;
	} else {
		if(yych <= ')') goto yy178;
		if(yych == ';') goto yy178;
		goto yy179;
	}
yy168:
	++YYCURSOR;
	{u_fprintf(ux_stderr, "Error: Unexpected ( on line %u!\n", result->lines); exit(1);}
yy170:
	++YYCURSOR;
	{u_fprintf(ux_stderr, "Error: Unexpected ) on line %u!\n", result->lines); exit(1);}
yy172:
	++YYCURSOR;
	{
		YYCURSOR = re2c_skipline(YYCURSOR);
		marker = YYCURSOR;
		goto parsePreferredTargets_start;
		}
yy174:
	++YYCURSOR;
	{goto parsePreferredTargets_end;}
yy176:
	++YYCURSOR;
	{
		marker = YYCURSOR;
		goto parsePreferredTargets_start;
		}
yy178:
	++YYCURSOR;
	yych = *YYCURSOR;
yy179:
	if(yych <= ')') {
		if(yych <= ' ') {
			if(yych <= 0x00000008) goto yy178;
			if(yych <= 0x0000000D) goto yy166;
			if(yych <= 0x0000001B) goto yy178;
			goto yy166;
		} else {
			if(yych == '#') goto yy166;
			if(yych <= '\'') goto yy178;
			goto yy166;
		}
	} else {
		if(yych <= '\\') {
			if(yych == ';') goto yy166;
			if(yych <= '[') goto yy178;
		} else {
			if(yych <= 0x00000085) {
				if(yych <= 0x00000084) goto yy178;
				goto yy166;
			} else {
				if(yych <= 0x00002027) goto yy178;
				if(yych <= 0x00002029) goto yy166;
				goto yy178;
			}
		}
	}
yy180:
	++YYCURSOR;
	yych = *YYCURSOR;
	if(yych <= '[') {
		if(yych <= 0x0000000D) {
			if(yych <= 0x00000008) goto yy178;
			goto yy166;
		} else {
			if(yych <= 0x0000001B) goto yy178;
			if(yych <= ' ') goto yy166;
			goto yy178;
		}
	} else {
		if(yych <= 0x00000085) {
			if(yych <= '\\') goto yy180;
			if(yych <= 0x00000084) goto yy178;
			goto yy166;
		} else {
			if(yych <= 0x00002027) goto yy178;
			if(yych <= 0x00002029) goto yy166;
			goto yy178;
		}
	}
}


parsePreferredTargets_end:
	if (result->preferred_targets.empty()) {
		u_fprintf(ux_stderr, "Warning: PREFERRED-TARGETS was declared with no elements on line %u.\n", result->lines);
	}
	return YYCURSOR;
}

KEYWORDS GrammarParser::re2c_scan(YYCTYPE *input) {
	KEYWORDS retval = K_IGNORE;
	YYCTYPE *YYMARKER = 0;
	marker = YYCURSOR;
	
scan_start:

{
	YYCTYPE yych;
	yych = *YYCURSOR;
	if(yych <= 'O') {
		if(yych <= ':') {
			if(yych <= 0x0000000D) {
				if(yych <= 0x00000009) {
					if(yych <= 0x00000000) goto yy184;
					if(yych <= 0x00000008) goto yy205;
					goto yy188;
				} else {
					if(yych == 0x0000000B) goto yy188;
					if(yych <= 0x0000000C) goto yy186;
					goto yy188;
				}
			} else {
				if(yych <= '"') {
					if(yych <= 0x0000001B) goto yy205;
					if(yych <= ' ') goto yy188;
					goto yy205;
				} else {
					if(yych <= '#') goto yy203;
					if(yych <= '\'') goto yy205;
					if(yych <= ')') goto yy207;
					goto yy205;
				}
			}
		} else {
			if(yych <= 'E') {
				if(yych <= 'A') {
					if(yych <= ';') goto yy207;
					if(yych <= '@') goto yy205;
					goto yy193;
				} else {
					if(yych <= 'B') goto yy192;
					if(yych <= 'C') goto yy197;
					if(yych <= 'D') goto yy198;
					goto yy199;
				}
			} else {
				if(yych <= 'J') {
					if(yych <= 'H') goto yy205;
					if(yych <= 'I') goto yy202;
					goto yy200;
				} else {
					if(yych <= 'K') goto yy205;
					if(yych <= 'L') goto yy201;
					if(yych <= 'M') goto yy194;
					goto yy205;
				}
			}
		}
	} else {
		if(yych <= 'i') {
			if(yych <= '`') {
				if(yych <= 'R') {
					if(yych <= 'P') goto yy190;
					if(yych <= 'Q') goto yy205;
					goto yy195;
				} else {
					if(yych <= 'S') goto yy196;
					if(yych == '\\') goto yy206;
					goto yy205;
				}
			} else {
				if(yych <= 'c') {
					if(yych <= 'a') goto yy193;
					if(yych <= 'b') goto yy192;
					goto yy197;
				} else {
					if(yych <= 'd') goto yy198;
					if(yych <= 'e') goto yy199;
					if(yych <= 'h') goto yy205;
					goto yy202;
				}
			}
		} else {
			if(yych <= 'q') {
				if(yych <= 'l') {
					if(yych <= 'j') goto yy200;
					if(yych <= 'k') goto yy205;
					goto yy201;
				} else {
					if(yych <= 'm') goto yy194;
					if(yych == 'p') goto yy190;
					goto yy205;
				}
			} else {
				if(yych <= 0x00000085) {
					if(yych <= 'r') goto yy195;
					if(yych <= 's') goto yy196;
					if(yych <= 0x00000084) goto yy205;
					goto yy186;
				} else {
					if(yych <= 0x00002027) goto yy205;
					if(yych <= 0x00002029) goto yy186;
					if(yych <= 0x0000FFFF) goto yy205;
				}
			}
		}
	}
yy184:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy185;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy185;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy185;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy185:
	{retval = K_IGNORE; goto scan_end;}
yy186:
	++YYCURSOR;
	{marker = YYCURSOR; result->lines++; goto scan_start;}
yy188:
	++YYCURSOR;
	{goto scan_start;}
yy190:
	++YYCURSOR;
	if((yych = *YYCURSOR) == 'R') goto yy392;
	if(yych == 'r') goto yy392;
	goto yy210;
yy191:
	{goto scan_start;}
yy192:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy377;
	if(yych == 'e') goto yy377;
	goto yy210;
yy193:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'B':
	case 'b':	goto yy343;
	case 'D':
	case 'd':	goto yy344;
	case 'F':
	case 'f':	goto yy345;
	case 'N':
	case 'n':	goto yy346;
	case 'P':
	case 'p':	goto yy347;
	default:	goto yy210;
	}
yy194:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy322;
	if(yych == 'a') goto yy322;
	goto yy210;
yy195:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy301;
	if(yych == 'e') goto yy301;
	goto yy210;
yy196:
	yych = *++YYCURSOR;
	if(yych <= 'U') {
		if(yych == 'E') goto yy266;
		if(yych <= 'T') goto yy210;
		goto yy267;
	} else {
		if(yych <= 'e') {
			if(yych <= 'd') goto yy210;
			goto yy266;
		} else {
			if(yych == 'u') goto yy267;
			goto yy210;
		}
	}
yy197:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy245;
	if(yych == 'o') goto yy245;
	goto yy210;
yy198:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy234;
	if(yych == 'e') goto yy234;
	goto yy210;
yy199:
	yych = *++YYCURSOR;
	if(yych <= 'X') {
		if(yych == 'N') goto yy224;
		if(yych <= 'W') goto yy210;
		goto yy225;
	} else {
		if(yych <= 'n') {
			if(yych <= 'm') goto yy210;
			goto yy224;
		} else {
			if(yych == 'x') goto yy225;
			goto yy210;
		}
	}
yy200:
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy220;
	if(yych == 'u') goto yy220;
	goto yy210;
yy201:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy216;
	if(yych == 'i') goto yy216;
	goto yy210;
yy202:
	yych = *++YYCURSOR;
	if(yych == 'F') goto yy213;
	if(yych == 'f') goto yy213;
	goto yy210;
yy203:
	++YYCURSOR;
	{YYCURSOR = re2c_skipline(YYCURSOR); marker = YYCURSOR; goto scan_start;}
yy205:
	yych = *++YYCURSOR;
	goto yy210;
yy206:
	yych = *++YYCURSOR;
	if(yych <= '\'') {
		if(yych == '#') goto yy209;
		goto yy210;
	} else {
		if(yych <= ')') goto yy209;
		if(yych == ';') goto yy209;
		goto yy210;
	}
yy207:
	++YYCURSOR;
	{u_fprintf(ux_stderr, "Error: Unexpected input on line %u!\n", result->lines); goto scan_end;}
yy209:
	++YYCURSOR;
	yych = *YYCURSOR;
yy210:
	if(yych <= ')') {
		if(yych <= ' ') {
			if(yych <= 0x00000008) goto yy209;
			if(yych <= 0x0000000D) goto yy191;
			if(yych <= 0x0000001B) goto yy209;
			goto yy191;
		} else {
			if(yych == '#') goto yy191;
			if(yych <= '\'') goto yy209;
			goto yy191;
		}
	} else {
		if(yych <= '\\') {
			if(yych == ';') goto yy191;
			if(yych <= '[') goto yy209;
		} else {
			if(yych <= 0x00000085) {
				if(yych <= 0x00000084) goto yy209;
				goto yy191;
			} else {
				if(yych <= 0x00002027) goto yy209;
				if(yych <= 0x00002029) goto yy191;
				goto yy209;
			}
		}
	}
yy211:
	++YYCURSOR;
	yych = *YYCURSOR;
	if(yych <= '[') {
		if(yych <= 0x0000000D) {
			if(yych <= 0x00000008) goto yy209;
			goto yy191;
		} else {
			if(yych <= 0x0000001B) goto yy209;
			if(yych <= ' ') goto yy191;
			goto yy209;
		}
	} else {
		if(yych <= 0x00000085) {
			if(yych <= '\\') goto yy211;
			if(yych <= 0x00000084) goto yy209;
			goto yy191;
		} else {
			if(yych <= 0x00002027) goto yy209;
			if(yych <= 0x00002029) goto yy191;
			goto yy209;
		}
	}
yy213:
	yych = *++YYCURSOR;
	if(yych == 'F') goto yy214;
	if(yych != 'f') goto yy210;
yy214:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy215;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy215;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy215;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy215:
	{goto scan_start;}
yy216:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy217;
	if(yych != 's') goto yy210;
yy217:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy218;
	if(yych != 't') goto yy210;
yy218:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy219;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy219;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy219;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy219:
	{YYCURSOR = re2c_parseList(YYCURSOR); marker = YYCURSOR; goto scan_start;}
yy220:
	yych = *++YYCURSOR;
	if(yych == 'M') goto yy221;
	if(yych != 'm') goto yy210;
yy221:
	yych = *++YYCURSOR;
	if(yych == 'P') goto yy222;
	if(yych != 'p') goto yy210;
yy222:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy223;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy223;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy223;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy223:
	{goto scan_start;}
yy224:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy232;
	if(yych == 'd') goto yy232;
	goto yy210;
yy225:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy226;
	if(yych != 'e') goto yy210;
yy226:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy227;
	if(yych != 'c') goto yy210;
yy227:
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy228;
	if(yych != 'u') goto yy210;
yy228:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy229;
	if(yych != 't') goto yy210;
yy229:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy230;
	if(yych != 'e') goto yy210;
yy230:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy231;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy231;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy231;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy231:
	{goto scan_start;}
yy232:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy233;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy233;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy233;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy233:
	{retval = K_IGNORE; goto scan_end;}
yy234:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy235;
	if(yych != 'l') goto yy210;
yy235:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy236;
	if(yych != 'i') goto yy210;
yy236:
	yych = *++YYCURSOR;
	if(yych == 'M') goto yy237;
	if(yych != 'm') goto yy210;
yy237:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy238;
	if(yych != 'i') goto yy210;
yy238:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy239;
	if(yych != 't') goto yy210;
yy239:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ':') {
		if(yych <= ' ') {
			if(yych <= 0x00000008) goto yy210;
			if(yych <= 0x0000000D) goto yy240;
			if(yych <= 0x0000001B) goto yy210;
		} else {
			if(yych <= '#') {
				if(yych <= '"') goto yy210;
			} else {
				if(yych <= '\'') goto yy210;
				if(yych >= '*') goto yy210;
			}
		}
	} else {
		if(yych <= 'e') {
			if(yych <= 'D') {
				if(yych >= '<') goto yy210;
			} else {
				if(yych <= 'E') goto yy241;
				if(yych <= 'd') goto yy210;
				goto yy241;
			}
		} else {
			if(yych <= 0x00000085) {
				if(yych <= 0x00000084) goto yy210;
			} else {
				if(yych <= 0x00002027) goto yy210;
				if(yych >= 0x0000202A) goto yy210;
			}
		}
	}
yy240:
	{goto scan_start;}
yy241:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy242;
	if(yych != 'r') goto yy210;
yy242:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy243;
	if(yych != 's') goto yy210;
yy243:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy244;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy244;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy244;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy244:
	{YYCURSOR = re2c_parseDelimiters(YYCURSOR); marker = YYCURSOR; goto scan_start;}
yy245:
	yych = *++YYCURSOR;
	if(yych <= 'R') {
		if(yych == 'N') goto yy247;
		if(yych <= 'Q') goto yy210;
	} else {
		if(yych <= 'n') {
			if(yych <= 'm') goto yy210;
			goto yy247;
		} else {
			if(yych != 'r') goto yy210;
		}
	}
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy257;
	if(yych == 'r') goto yy257;
	goto yy210;
yy247:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy248;
	if(yych != 's') goto yy210;
yy248:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy249;
	if(yych != 't') goto yy210;
yy249:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy250;
	if(yych != 'r') goto yy210;
yy250:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy251;
	if(yych != 'a') goto yy210;
yy251:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy252;
	if(yych != 'i') goto yy210;
yy252:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy253;
	if(yych != 'n') goto yy210;
yy253:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy254;
	if(yych != 't') goto yy210;
yy254:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy255;
	if(yych != 's') goto yy210;
yy255:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy256;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy256;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy256;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy256:
	{goto scan_start;}
yy257:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy258;
	if(yych != 'e') goto yy210;
yy258:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy259;
	if(yych != 'c') goto yy210;
yy259:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy260;
	if(yych != 't') goto yy210;
yy260:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy261;
	if(yych != 'i') goto yy210;
yy261:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy262;
	if(yych != 'o') goto yy210;
yy262:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy263;
	if(yych != 'n') goto yy210;
yy263:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy264;
	if(yych != 's') goto yy210;
yy264:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy265;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy265;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy265;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy265:
	{goto scan_start;}
yy266:
	yych = *++YYCURSOR;
	if(yych <= 'T') {
		if(yych <= 'K') {
			if(yych == 'C') goto yy279;
			goto yy210;
		} else {
			if(yych <= 'L') goto yy280;
			if(yych <= 'S') goto yy210;
			goto yy277;
		}
	} else {
		if(yych <= 'k') {
			if(yych == 'c') goto yy279;
			goto yy210;
		} else {
			if(yych <= 'l') goto yy280;
			if(yych == 't') goto yy277;
			goto yy210;
		}
	}
yy267:
	yych = *++YYCURSOR;
	if(yych == 'B') goto yy268;
	if(yych != 'b') goto yy210;
yy268:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy269;
	if(yych != 's') goto yy210;
yy269:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy270;
	if(yych != 't') goto yy210;
yy270:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy271;
	if(yych != 'i') goto yy210;
yy271:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy272;
	if(yych != 't') goto yy210;
yy272:
	yych = *++YYCURSOR;
	if(yych == 'U') goto yy273;
	if(yych != 'u') goto yy210;
yy273:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy274;
	if(yych != 't') goto yy210;
yy274:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy275;
	if(yych != 'e') goto yy210;
yy275:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy276;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy276;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy276;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy276:
	{goto scan_start;}
yy277:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'R') {
		if(yych <= '"') {
			if(yych <= 0x0000000D) {
				if(yych <= 0x00000008) goto yy210;
			} else {
				if(yych <= 0x0000001B) goto yy210;
				if(yych >= '!') goto yy210;
			}
		} else {
			if(yych <= ')') {
				if(yych <= '#') goto yy278;
				if(yych <= '\'') goto yy210;
			} else {
				if(yych != ';') goto yy210;
			}
		}
	} else {
		if(yych <= 'u') {
			if(yych <= 'V') {
				if(yych <= 'S') goto yy290;
				if(yych <= 'U') goto yy210;
				goto yy292;
			} else {
				if(yych == 's') goto yy290;
				goto yy210;
			}
		} else {
			if(yych <= 0x00000085) {
				if(yych <= 'v') goto yy292;
				if(yych <= 0x00000084) goto yy210;
			} else {
				if(yych <= 0x00002027) goto yy210;
				if(yych >= 0x0000202A) goto yy210;
			}
		}
	}
yy278:
	{YYCURSOR = re2c_parseSet(YYCURSOR); marker = YYCURSOR; goto scan_start;}
yy279:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy285;
	if(yych == 't') goto yy285;
	goto yy210;
yy280:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy281;
	if(yych != 'e') goto yy210;
yy281:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy282;
	if(yych != 'c') goto yy210;
yy282:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy283;
	if(yych != 't') goto yy210;
yy283:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy284;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy284;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy284;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy284:
	{goto scan_start;}
yy285:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy286;
	if(yych != 'i') goto yy210;
yy286:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy287;
	if(yych != 'o') goto yy210;
yy287:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy288;
	if(yych != 'n') goto yy210;
yy288:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy289;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy289;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy289;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy289:
	{goto scan_start;}
yy290:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy291;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy291;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy291;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy291:
	{goto scan_start;}
yy292:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy293;
	if(yych != 'a') goto yy210;
yy293:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy294;
	if(yych != 'r') goto yy210;
yy294:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy295;
	if(yych != 'i') goto yy210;
yy295:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy296;
	if(yych != 'a') goto yy210;
yy296:
	yych = *++YYCURSOR;
	if(yych == 'B') goto yy297;
	if(yych != 'b') goto yy210;
yy297:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy298;
	if(yych != 'l') goto yy210;
yy298:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy299;
	if(yych != 'e') goto yy210;
yy299:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy300;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy300;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy300;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy300:
	{goto scan_start;}
yy301:
	yych = *++YYCURSOR;
	if(yych <= 'P') {
		if(yych == 'M') goto yy302;
		if(yych <= 'O') goto yy210;
		goto yy303;
	} else {
		if(yych <= 'm') {
			if(yych <= 'l') goto yy210;
		} else {
			if(yych == 'p') goto yy303;
			goto yy210;
		}
	}
yy302:
	yych = *++YYCURSOR;
	if(yych <= 'V') {
		if(yych == 'O') goto yy309;
		if(yych <= 'U') goto yy210;
		goto yy310;
	} else {
		if(yych <= 'o') {
			if(yych <= 'n') goto yy210;
			goto yy309;
		} else {
			if(yych == 'v') goto yy310;
			goto yy210;
		}
	}
yy303:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy304;
	if(yych != 'l') goto yy210;
yy304:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy305;
	if(yych != 'a') goto yy210;
yy305:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy306;
	if(yych != 'c') goto yy210;
yy306:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy307;
	if(yych != 'e') goto yy210;
yy307:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy308;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy308;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy308;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy308:
	{goto scan_start;}
yy309:
	yych = *++YYCURSOR;
	if(yych == 'V') goto yy319;
	if(yych == 'v') goto yy319;
	goto yy210;
yy310:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy311;
	if(yych != 'a') goto yy210;
yy311:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy312;
	if(yych != 'r') goto yy210;
yy312:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy313;
	if(yych != 'i') goto yy210;
yy313:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy314;
	if(yych != 'a') goto yy210;
yy314:
	yych = *++YYCURSOR;
	if(yych == 'B') goto yy315;
	if(yych != 'b') goto yy210;
yy315:
	yych = *++YYCURSOR;
	if(yych == 'L') goto yy316;
	if(yych != 'l') goto yy210;
yy316:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy317;
	if(yych != 'e') goto yy210;
yy317:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy318;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy318;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy318;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy318:
	{goto scan_start;}
yy319:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy320;
	if(yych != 'e') goto yy210;
yy320:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy321;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy321;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy321;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy321:
	{goto scan_start;}
yy322:
	yych = *++YYCURSOR;
	if(yych <= 'T') {
		if(yych == 'P') goto yy323;
		if(yych <= 'S') goto yy210;
		goto yy325;
	} else {
		if(yych <= 'p') {
			if(yych <= 'o') goto yy210;
		} else {
			if(yych == 't') goto yy325;
			goto yy210;
		}
	}
yy323:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= ':') {
		if(yych <= ' ') {
			if(yych <= 0x00000008) goto yy210;
			if(yych <= 0x0000000D) goto yy324;
			if(yych <= 0x0000001B) goto yy210;
		} else {
			if(yych <= '#') {
				if(yych <= '"') goto yy210;
			} else {
				if(yych <= '\'') goto yy210;
				if(yych >= '*') goto yy210;
			}
		}
	} else {
		if(yych <= 'p') {
			if(yych <= 'O') {
				if(yych >= '<') goto yy210;
			} else {
				if(yych <= 'P') goto yy329;
				if(yych <= 'o') goto yy210;
				goto yy329;
			}
		} else {
			if(yych <= 0x00000085) {
				if(yych <= 0x00000084) goto yy210;
			} else {
				if(yych <= 0x00002027) goto yy210;
				if(yych >= 0x0000202A) goto yy210;
			}
		}
	}
yy324:
	{goto scan_start;}
yy325:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy326;
	if(yych != 'c') goto yy210;
yy326:
	yych = *++YYCURSOR;
	if(yych == 'H') goto yy327;
	if(yych != 'h') goto yy210;
yy327:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy328;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy328;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy328;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy328:
	{goto scan_start;}
yy329:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy330;
	if(yych != 'i') goto yy210;
yy330:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy331;
	if(yych != 'n') goto yy210;
yy331:
	yych = *++YYCURSOR;
	if(yych == 'G') goto yy332;
	if(yych != 'g') goto yy210;
yy332:
	yych = *++YYCURSOR;
	if(yych <= 'R') {
		if(yych != '-') goto yy210;
	} else {
		if(yych <= 'S') goto yy334;
		if(yych == 's') goto yy334;
		goto yy210;
	}
	yych = *++YYCURSOR;
	if(yych == 'P') goto yy336;
	if(yych == 'p') goto yy336;
	goto yy210;
yy334:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy335;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy335;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy335;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy335:
	{goto scan_start;}
yy336:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy337;
	if(yych != 'r') goto yy210;
yy337:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy338;
	if(yych != 'e') goto yy210;
yy338:
	yych = *++YYCURSOR;
	if(yych == 'F') goto yy339;
	if(yych != 'f') goto yy210;
yy339:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy340;
	if(yych != 'i') goto yy210;
yy340:
	yych = *++YYCURSOR;
	if(yych == 'X') goto yy341;
	if(yych != 'x') goto yy210;
yy341:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy342;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy342;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy342;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy342:
	{goto scan_start;}
yy343:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy373;
	if(yych == 'o') goto yy373;
	goto yy210;
yy344:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy371;
	if(yych == 'd') goto yy371;
	goto yy210;
yy345:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy358;
	if(yych == 't') goto yy358;
	goto yy210;
yy346:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy353;
	if(yych == 'c') goto yy353;
	goto yy210;
yy347:
	yych = *++YYCURSOR;
	if(yych == 'P') goto yy348;
	if(yych != 'p') goto yy210;
yy348:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy349;
	if(yych != 'e') goto yy210;
yy349:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy350;
	if(yych != 'n') goto yy210;
yy350:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy351;
	if(yych != 'd') goto yy210;
yy351:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy352;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy352;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy352;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy352:
	{goto scan_start;}
yy353:
	yych = *++YYCURSOR;
	if(yych == 'H') goto yy354;
	if(yych != 'h') goto yy210;
yy354:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy355;
	if(yych != 'o') goto yy210;
yy355:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy356;
	if(yych != 'r') goto yy210;
yy356:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy357;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy357;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy357;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy357:
	{goto scan_start;}
yy358:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy359;
	if(yych != 'e') goto yy210;
yy359:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy360;
	if(yych != 'r') goto yy210;
yy360:
	yych = *++YYCURSOR;
	if(yych != '-') goto yy210;
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy362;
	if(yych != 's') goto yy210;
yy362:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy363;
	if(yych != 'e') goto yy210;
yy363:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy364;
	if(yych != 'c') goto yy210;
yy364:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy365;
	if(yych != 't') goto yy210;
yy365:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy366;
	if(yych != 'i') goto yy210;
yy366:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy367;
	if(yych != 'o') goto yy210;
yy367:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy368;
	if(yych != 'n') goto yy210;
yy368:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy369;
	if(yych != 's') goto yy210;
yy369:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy370;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy370;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy370;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy370:
	{goto scan_start;}
yy371:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy372;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy372;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy372;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy372:
	{goto scan_start;}
yy373:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy374;
	if(yych != 'r') goto yy210;
yy374:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy375;
	if(yych != 't') goto yy210;
yy375:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy376;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy376;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy376;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy376:
	{goto scan_start;}
yy377:
	yych = *++YYCURSOR;
	if(yych == 'F') goto yy378;
	if(yych != 'f') goto yy210;
yy378:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy379;
	if(yych != 'o') goto yy210;
yy379:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy380;
	if(yych != 'r') goto yy210;
yy380:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy381;
	if(yych != 'e') goto yy210;
yy381:
	yych = *++YYCURSOR;
	if(yych != '-') goto yy210;
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy383;
	if(yych != 's') goto yy210;
yy383:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy384;
	if(yych != 'e') goto yy210;
yy384:
	yych = *++YYCURSOR;
	if(yych == 'C') goto yy385;
	if(yych != 'c') goto yy210;
yy385:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy386;
	if(yych != 't') goto yy210;
yy386:
	yych = *++YYCURSOR;
	if(yych == 'I') goto yy387;
	if(yych != 'i') goto yy210;
yy387:
	yych = *++YYCURSOR;
	if(yych == 'O') goto yy388;
	if(yych != 'o') goto yy210;
yy388:
	yych = *++YYCURSOR;
	if(yych == 'N') goto yy389;
	if(yych != 'n') goto yy210;
yy389:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy390;
	if(yych != 's') goto yy210;
yy390:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy391;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy391;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy391;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy391:
	{goto scan_start;}
yy392:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy393;
	if(yych != 'e') goto yy210;
yy393:
	yych = *++YYCURSOR;
	if(yych == 'F') goto yy394;
	if(yych != 'f') goto yy210;
yy394:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy395;
	if(yych != 'e') goto yy210;
yy395:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy396;
	if(yych != 'r') goto yy210;
yy396:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy397;
	if(yych != 'r') goto yy210;
yy397:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy398;
	if(yych != 'e') goto yy210;
yy398:
	yych = *++YYCURSOR;
	if(yych == 'D') goto yy399;
	if(yych != 'd') goto yy210;
yy399:
	yych = *++YYCURSOR;
	if(yych != '-') goto yy210;
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy401;
	if(yych != 't') goto yy210;
yy401:
	yych = *++YYCURSOR;
	if(yych == 'A') goto yy402;
	if(yych != 'a') goto yy210;
yy402:
	yych = *++YYCURSOR;
	if(yych == 'R') goto yy403;
	if(yych != 'r') goto yy210;
yy403:
	yych = *++YYCURSOR;
	if(yych == 'G') goto yy404;
	if(yych != 'g') goto yy210;
yy404:
	yych = *++YYCURSOR;
	if(yych == 'E') goto yy405;
	if(yych != 'e') goto yy210;
yy405:
	yych = *++YYCURSOR;
	if(yych == 'T') goto yy406;
	if(yych != 't') goto yy210;
yy406:
	yych = *++YYCURSOR;
	if(yych == 'S') goto yy407;
	if(yych != 's') goto yy210;
yy407:
	++YYCURSOR;
	if((yych = *YYCURSOR) <= '\'') {
		if(yych <= 0x0000001B) {
			if(yych <= 0x00000008) goto yy210;
			if(yych >= 0x0000000E) goto yy210;
		} else {
			if(yych <= ' ') goto yy408;
			if(yych != '#') goto yy210;
		}
	} else {
		if(yych <= 0x00000084) {
			if(yych <= ')') goto yy408;
			if(yych != ';') goto yy210;
		} else {
			if(yych <= 0x00000085) goto yy408;
			if(yych <= 0x00002027) goto yy210;
			if(yych >= 0x0000202A) goto yy210;
		}
	}
yy408:
	{YYCURSOR = re2c_parsePreferredTargets(YYCURSOR); marker = YYCURSOR; goto scan_start;}
}


scan_end:
	marker = 0;
	return retval;
}

int GrammarParser::re2c_grammar_from_ufile(UFILE *input) {
	u_frewind(input);
	if (u_feof(input)) {
		u_fprintf(ux_stderr, "Error: Input is null - nothing to parse!\n");
		return -1;
	}
	if (!result) {
		u_fprintf(ux_stderr, "Error: No preallocated grammar provided - cannot continue!\n");
		return -1;
	}
	
	free_keywords();
	free_regexps();
	free_strings();

	int error = init_keywords();
	if (error) {
		u_fprintf(ux_stderr, "Error: init_keywords returned %i!\n", error);
		return error;
	}

	error = init_regexps();
	if (error) {
		u_fprintf(ux_stderr, "Error: init_regexps returned %i!\n", error);
		return error;
	}

	error = init_strings();
	if (error) {
		u_fprintf(ux_stderr, "Error: init_strings returned %i!\n", error);
		return error;
	}

	UChar *buffer = new UChar[result->grammar_size+8];
	memset(buffer, 0, sizeof(UChar)*(result->grammar_size+8));
	u_file_read(buffer, result->grammar_size, input);
	
	UChar *offset = buffer;
	if (u_strlen(offset) > 0) {
		result->lines = 1;
		re2c_scan(offset);
	} else {
		u_fprintf(ux_stderr, "Error: Grammar file is empty - nothing to parse!\n");
		return -1;
	}
	
	delete buffer;
	free_regexps();
	free_strings();

	return 0;
}
