/*
* Copyright (C) 2007-2021, GrammarSoft ApS
* Developed by Tino Didriksen <mail@tinodidriksen.com>
* Design by Eckhard Bick <eckhard.bick@mail.dk>, Tino Didriksen <mail@tinodidriksen.com>
*
* This file is part of VISL CG-3
*
* VISL CG-3 is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* VISL CG-3 is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with VISL CG-3.  If not, see <http://www.gnu.org/licenses/>.
*/

#pragma once
#ifndef c6d28b7452ec699b_STRINGS_H
#define c6d28b7452ec699b_STRINGS_H

#include <cstdint>

namespace CG3 {
// ToDo: Add ABORT
enum KEYWORDS : uint32_t {
	K_IGNORE,
	K_SETS,
	K_LIST,
	K_SET,
	K_DELIMITERS,
	K_SOFT_DELIMITERS,
	K_PREFERRED_TARGETS,
	K_MAPPING_PREFIX,
	K_MAPPINGS,
	K_CONSTRAINTS,
	K_CORRECTIONS,
	K_SECTION,
	K_BEFORE_SECTIONS,
	K_AFTER_SECTIONS,
	K_NULL_SECTION,
	K_ADD,
	K_MAP,
	K_REPLACE,
	K_SELECT,
	K_REMOVE,
	K_IFF,
	K_APPEND,
	K_SUBSTITUTE,
	K_START,
	K_END,
	K_ANCHOR,
	K_EXECUTE,
	K_JUMP,
	K_REMVARIABLE,
	K_SETVARIABLE,
	K_DELIMIT,
	K_MATCH,
	K_SETPARENT,
	K_SETCHILD,
	K_ADDRELATION,
	K_SETRELATION,
	K_REMRELATION,
	K_ADDRELATIONS,
	K_SETRELATIONS,
	K_REMRELATIONS,
	K_TEMPLATE,
	K_MOVE,
	K_MOVE_AFTER,
	K_MOVE_BEFORE,
	K_SWITCH,
	K_REMCOHORT,
	K_STATIC_SETS,
	K_UNMAP,
	K_COPY,
	K_ADDCOHORT,
	K_ADDCOHORT_AFTER,
	K_ADDCOHORT_BEFORE,
	K_EXTERNAL,
	K_EXTERNAL_ONCE,
	K_EXTERNAL_ALWAYS,
	K_OPTIONS,
	K_STRICT_TAGS,
	K_REOPEN_MAPPINGS,
	K_SUBREADINGS,
	K_SPLITCOHORT,
	K_PROTECT,
	K_UNPROTECT,
	K_MERGECOHORTS,
	K_RESTORE,
	KEYWORD_COUNT,
};

enum : uint32_t {
	S_IGNORE,
	S_OR = 3,
	S_PLUS,
	S_MINUS,
	S_FAILFAST = 8,
	S_SET_DIFF,
	S_SET_ISECT_U,
	S_SET_SYMDIFF_U,
};

// This must be kept in lock-step with Rule.hpp's RULE_FLAGS
enum : uint32_t {
	FL_NEAREST,
	FL_ALLOWLOOP,
	FL_DELAYED,
	FL_IMMEDIATE,
	FL_LOOKDELETED,
	FL_LOOKDELAYED,
	FL_UNSAFE,
	FL_SAFE,
	FL_REMEMBERX,
	FL_RESETX,
	FL_KEEPORDER,
	FL_VARYORDER,
	FL_ENCL_INNER,
	FL_ENCL_OUTER,
	FL_ENCL_FINAL,
	FL_ENCL_ANY,
	FL_ALLOWCROSS,
	FL_WITHCHILD,
	FL_NOCHILD,
	FL_ITERATE,
	FL_NOITERATE,
	FL_UNMAPLAST,
	FL_REVERSE,
	FL_SUB,
	FL_OUTPUT,
	FL_CAPTURE_UNIF,
	FL_REPEAT,
	FL_BEFORE,
	FL_AFTER,
	FL_IGNORED,
	FL_LOOKIGNORED,
	FLAGS_COUNT,
};
}

#include "stdafx.hpp"

namespace CG3 {
constexpr UStringView g_flags[FLAGS_COUNT] = {
	u"NEAREST"_usv,
	u"ALLOWLOOP"_usv,
	u"DELAYED"_usv,
	u"IMMEDIATE"_usv,
	u"LOOKDELETED"_usv,
	u"LOOKDELAYED"_usv,
	u"UNSAFE"_usv,
	u"SAFE"_usv,
	u"REMEMBERX"_usv,
	u"RESETX"_usv,
	u"KEEPORDER"_usv,
	u"VARYORDER"_usv,
	u"ENCL_INNER"_usv,
	u"ENCL_OUTER"_usv,
	u"ENCL_FINAL"_usv,
	u"ENCL_ANY"_usv,
	u"ALLOWCROSS"_usv,
	u"WITHCHILD"_usv,
	u"NOCHILD"_usv,
	u"ITERATE"_usv,
	u"NOITERATE"_usv,
	u"UNMAPLAST"_usv,
	u"REVERSE"_usv,
	u"SUB"_usv,
	u"OUTPUT"_usv,
	u"CAPTURE_UNIF"_usv,
	u"REPEAT"_usv,
	u"BEFORE"_usv,
	u"AFTER"_usv,
	u"IGNORED"_usv,
	u"LOOKIGNORED"_usv,
};

constexpr UStringView keywords[KEYWORD_COUNT] = {
	u"__CG3_DUMMY_KEYWORD__"_usv,
	u"SETS"_usv,
	u"LIST"_usv,
	u"SET"_usv,
	u"DELIMITERS"_usv,
	u"SOFT-DELIMITERS"_usv,
	u"PREFERRED-TARGETS"_usv,
	u"MAPPING-PREFIX"_usv,
	u"MAPPINGS"_usv,
	u"CONSTRAINTS"_usv,
	u"CORRECTIONS"_usv,
	u"SECTION"_usv,
	u"BEFORE-SECTIONS"_usv,
	u"AFTER-SECTIONS"_usv,
	u"NULL-SECTION"_usv,
	u"ADD"_usv,
	u"MAP"_usv,
	u"REPLACE"_usv,
	u"SELECT"_usv,
	u"REMOVE"_usv,
	u"IFF"_usv,
	u"APPEND"_usv,
	u"SUBSTITUTE"_usv,
	u"START"_usv,
	u"END"_usv,
	u"ANCHOR"_usv,
	u"EXECUTE"_usv,
	u"JUMP"_usv,
	u"REMVARIABLE"_usv,
	u"SETVARIABLE"_usv,
	u"DELIMIT"_usv,
	u"MATCH"_usv,
	u"SETPARENT"_usv,
	u"SETCHILD"_usv,
	u"ADDRELATION"_usv,
	u"SETRELATION"_usv,
	u"REMRELATION"_usv,
	u"ADDRELATIONS"_usv,
	u"SETRELATIONS"_usv,
	u"REMRELATIONS"_usv,
	u"TEMPLATE"_usv,
	u"MOVE"_usv,
	u"MOVE-AFTER"_usv,
	u"MOVE-BEFORE"_usv,
	u"SWITCH"_usv,
	u"REMCOHORT"_usv,
	u"STATIC-SETS"_usv,
	u"UNMAP"_usv,
	u"COPY"_usv,
	u"ADDCOHORT"_usv,
	u"ADDCOHORT-AFTER"_usv,
	u"ADDCOHORT-BEFORE"_usv,
	u"EXTERNAL"_usv,
	u"EXTERNAL-ONCE"_usv,
	u"EXTERNAL-ALWAYS"_usv,
	u"OPTIONS"_usv,
	u"STRICT-TAGS"_usv,
	u"REOPEN-MAPPINGS"_usv,
	u"SUBREADINGS"_usv,
	u"SPLITCOHORT"_usv,
	u"PROTECT"_usv,
	u"UNPROTECT"_usv,
	u"MERGECOHORTS"_usv,
	u"RESTORE"_usv,
};

constexpr UStringView stringbits[] = {
	u""_usv,
	u""_usv,
	u""_usv,
	u"OR"_usv,
	u"+"_usv,
	u"-"_usv,
	u""_usv,
	u""_usv,
	u"^"_usv,
};

constexpr UStringView
	STR_TARGET{ u"TARGET"_usv },
	STR_AND{ u"AND"_usv },
	STR_IF{ u"IF"_usv },
	STR_OR{ u"OR"_usv },
	STR_TEXTNOT{ u"NOT"_usv },
	STR_TEXTNEGATE{ u"NEGATE"_usv },
	STR_ALL{ u"ALL"_usv },
	STR_NONE{ u"NONE"_usv },
	STR_LINK{ u"LINK"_usv },
	STR_TO{ u"TO"_usv },
	STR_FROM{ u"FROM"_usv },
	STR_AFTER{ u"AFTER"_usv },
	STR_BEFORE{ u"BEFORE"_usv },
	STR_WITH{ u"WITH"_usv },
	STR_ONCE{ u"ONCE"_usv },
	STR_ALWAYS{ u"ALWAYS"_usv },
	STR_EXCEPT{ u"EXCEPT"_usv },
	STR_STATIC{ u"STATIC"_usv },
	STR_ASTERIK{ u"*"_usv },
	STR_BARRIER{ u"BARRIER"_usv },
	STR_CBARRIER{ u"CBARRIER"_usv },
	STR_CMD_FLUSH{ u"<STREAMCMD:FLUSH>"_usv },
	STR_CMD_EXIT{ u"<STREAMCMD:EXIT>"_usv },
	STR_CMD_IGNORE{ u"<STREAMCMD:IGNORE>"_usv },
	STR_CMD_RESUME{ u"<STREAMCMD:RESUME>"_usv },
	STR_CMD_SETVAR{ u"<STREAMCMD:SETVAR:"_usv },
	STR_CMD_REMVAR{ u"<STREAMCMD:REMVAR:"_usv },
	STR_DELIMITSET{ u"_S_DELIMITERS_"_usv },
	STR_SOFTDELIMITSET{ u"_S_SOFT_DELIMITERS_"_usv },
	STR_TEXTDELIMITSET{ u"_S_TEXT_DELIMITERS_"_usv },
	STR_TEXTDELIM_DEFAULT{ u"/(^|\\n)</s/r"_usv },
	STR_BEGINTAG{ u">>>"_usv },
	STR_ENDTAG{ u"<<<"_usv },
	STR_UU_LEFT{ u"_LEFT_"_usv },
	STR_UU_RIGHT{ u"_RIGHT_"_usv },
	STR_UU_PAREN{ u"_PAREN_"_usv },
	STR_UU_TARGET{ u"_TARGET_"_usv },
	STR_UU_MARK{ u"_MARK_"_usv },
	STR_UU_ATTACHTO{ u"_ATTACHTO_"_usv },
	STR_UU_ENCL{ u"_ENCL_"_usv },
	STR_UU_SAME_BASIC{ u"_SAME_BASIC_"_usv },
	STR_RXTEXT_ANY{ u"<.*>"_usv },
	STR_RXBASE_ANY{ u"\".*\""_usv },
	STR_RXWORD_ANY{ u"\"<.*>\""_usv },
	STR_VS1{ u"$1"_usv },
	STR_VS2{ u"$2"_usv },
	STR_VS3{ u"$3"_usv },
	STR_VS4{ u"$4"_usv },
	STR_VS5{ u"$5"_usv },
	STR_VS6{ u"$6"_usv },
	STR_VS7{ u"$7"_usv },
	STR_VS8{ u"$8"_usv },
	STR_VS9{ u"$9"_usv },
	STR_VSu_raw{ u"%u"_usv },
	STR_VSU_raw{ u"%U"_usv },
	STR_VSl_raw{ u"%l"_usv },
	STR_VSL_raw{ u"%L"_usv },
	STR_VSu{ u"\x01u"_usv },
	STR_VSU{ u"\x01U"_usv },
	STR_VSl{ u"\x01l"_usv },
	STR_VSL{ u"\x01L"_usv },
	STR_GPREFIX{ u"_G_"_usv },
	STR_POSITIVE{ u"POSITIVE"_usv },
	STR_NEGATIVE{ u"NEGATIVE"_usv },
	STR_NO_ISETS{ u"no-inline-sets"_usv },
	STR_NO_ITMPLS{ u"no-inline-templates"_usv },
	STR_STRICT_WFORMS{ u"strict-wordforms"_usv },
	STR_STRICT_BFORMS{ u"strict-baseforms"_usv },
	STR_STRICT_SECOND{ u"strict-secondary"_usv },
	STR_STRICT_REGEX{ u"strict-regex"_usv },
	STR_STRICT_ICASE{ u"strict-icase"_usv },
	STR_SELF_NO_BARRIER{ u"self-no-barrier"_usv },
	STR_ORDERED{ u"ordered"_usv },
	STR_ADDCOHORT_ATTACH{ u"addcohort-attach"_usv },
	STR_DUMMY{ u"__CG3_DUMMY_STRINGBIT__"_usv }
	;

constexpr size_t CG3_BUFFER_SIZE = 8192;
constexpr size_t NUM_GBUFFERS = 1;
CG3_IMPORTS extern std::vector<UString> gbuffers;
constexpr size_t NUM_CBUFFERS = 1;
CG3_IMPORTS extern std::vector<std::string> cbuffers;

constexpr UChar not_sign = u'\u00AC';
}

#endif
