name: CG-3 CI Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: |
           sudo apt-get -qy update
           sudo apt-get -qfy install --no-install-recommends cmake build-essential libboost-dev libicu-dev libsqlite3-dev perl pkg-config python3-build python3-dev python3-pip python3-setuptools python3-virtualenv swig
    - name: cmake
      run: cmake -DENABLE_PYTHON_BINDINGS=ON .
    - name: build
      run: cmake --build . -v -j 4
    - name: test
      run: ctest -V
    - name: test suite
      run: ./test/runall.pl
    - name: install
      run: sudo cmake --install .
    - name: test python
      run: python3 -c "import constraint_grammar; print(dir(constraint_grammar))"
